---
title: "cellchat"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/Alyssa/Single_Cell_CHIP/")

library(Seurat)
library(tidyverse)

source("../scripts/image_formatting.R")
```

```{r}
devtools::install_github("sqjin/CellChat")
```

```{r}
library(CellChat)

# Generate Cell Chat Objects 
create_cc = function(seu_obj, nPatterns) {
  # creating cellchat object from steps of tutorial 
  cellchat = createCellChat(object = seu_obj, meta = seu_obj@meta.data, group.by = "cell_type") 
  CellChatDB = CellChatDB.human
  CellChatDB.use = CellChatDB
  cellchat@DB = CellChatDB.use
  #preprocessing
  cellchat = subsetData(cellchat)
  cellchat = identifyOverExpressedGenes(cellchat)
  cellchat = identifyOverExpressedInteractions(cellchat) # Identify over-expressed ligand-receptor interactions (pairs) within the used CellChatDB
  cellchat = projectData(cellchat, PPI.human) # A diffusion process is used to smooth genes’ expression values based on their neighbors’ defined in a high-confidence experimentally validated protein-protein network.
  cellchat = computeCommunProb(cellchat, type = 'truncatedMean', trim = 0.1) # calculating the average gene expression by discarding 10% from each end of the data 
  # Filter out the cell-cell communication if there are only few number of cells in certain cell groups
  cellchat = filterCommunication(cellchat, min.cells = 25) # Filter cell-cell communication if there are only few number of cells in certain cell groups
  cellchat = computeCommunProbPathway(cellchat) # Compute the communication probability on signaling pathway level by summarizing all related ligands/receptors
  cellchat = aggregateNet(cellchat) # Calculate the aggregated network by counting the number of links or summarizing the communication probability
  cellchat = netAnalysis_computeCentrality(cellchat, slot.name = "netP") # compute the network centrality scores allowing identification of dominant senders, receivers, mediators and influencers in all inferred communication networks 
  #outgoing patterns
  # selectK(cellchat, pattern = "outgoing") # ran before to determine best number for nPatterns 
  cellchat = identifyCommunicationPatterns(cellchat, pattern = "outgoing", k = nPatterns)
  #incoming patterns
  # selectK(cellchat, pattern = "incoming")
  cellchat = identifyCommunicationPatterns(cellchat, pattern = "incoming", k = nPatterns)
  return(cellchat)
}

diet_seurat_trimmed = readRDS("rds_objects/diet_seurat_trimmed.rds")

diet_seurat_trimmed@meta.data$cell_type[diet_seurat_trimmed@meta.data$cell_type == "CD14 Monos"] = "CD14+ Monocytes"
diet_seurat_trimmed@meta.data$cell_type[diet_seurat_trimmed@meta.data$cell_type == "CD16 Monos"] = "CD16+ Monocytes"
diet_seurat_trimmed@meta.data$cell_type[diet_seurat_trimmed@meta.data$cell_type == "B"] = "B cells"
diet_seurat_trimmed@meta.data$cell_type[diet_seurat_trimmed@meta.data$cell_type == "NK"] = "NK cells"


diet_seurat_trimmed.list = SplitObject(diet_seurat_trimmed, split.by = c("MUTATION.GROUP"))

diet_seurat_trimmed_tet2 = diet_seurat_trimmed.list$TET2
diet_seurat_trimmed_dnmt3a = diet_seurat_trimmed.list$DNMT3A
diet_seurat_trimmed_control = diet_seurat_trimmed.list$none

diet_cc_tet2 = create_cc(diet_seurat_trimmed_tet2, 3)
diet_cc_dnmt3a = create_cc(diet_seurat_trimmed_dnmt3a, 3)
diet_cc_control = create_cc(diet_seurat_trimmed_control, 3)

saveRDS(diet_cc_control, "rds_objects/diet_cc_control.rds")
saveRDS(diet_cc_tet2, "rds_objects/diet_cc_tet2.rds")
saveRDS(diet_cc_dnmt3a, "rds_objects/diet_cc_dnmt3a.rds")

```

```{r}


```

```{r}
diet_cc_control = readRDS("rds_objects/diet_cc_control.rds")
diet_cc_tet2 = readRDS("rds_objects/diet_cc_tet2.rds")
diet_cc_dnmt3a = readRDS("rds_objects/diet_cc_dnmt3a.rds")
```


```{r}
tet2_cc.list = list(TET2 = diet_cc_tet2, Control = diet_cc_control)
tet2_merged_cc = mergeCellChat(tet2_cc.list, add.names = names(tet2_cc.list))
tet2_merged_cc = updateCellChat(tet2_merged_cc)

dnmt3a_cc.list = list(DNMT3A = diet_cc_dnmt3a, Control = diet_cc_control)
dnmt3a_merged_cc = mergeCellChat(dnmt3a_cc.list, add.names = names(dnmt3a_cc.list))
dnmt3a_merged_cc = updateCellChat(dnmt3a_merged_cc)

all_cc.list = list(TET2 = diet_cc_tet2, DNMT3A = diet_cc_dnmt3a, Control = diet_cc_control)
all_merged_cc = mergeCellChat(all_cc.list, add.names = names(all_cc.list))
all_merged_cc = updateCellChat(all_merged_cc)
```

```{r}
rankNet(tet2_merged_cc, mode = "comparison", comparison = c(1,2), sources.use = "CD14+ Monocytes", signaling = c("MIF", "TNF"))
rankNet(dnmt3a_merged_cc, mode = "comparison", comparison = c(1,2), sources.use = "CD14 Monos", signaling = "MIF")
rankNet(all_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = "CD8+ T cells", signaling = "MIF")
rankNet(all_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = "NK", signaling = "IFN-II")

rankNet(all_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = "CD14 Monos", signaling = "CLEC")
rankNet(all_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = "CD8+ T cells", signaling = "CLEC")
rankNet(all_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = "CD4+ T cells", signaling = "CLEC")
rankNet(all_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = "NK", signaling = "CLEC")
rankNet(all_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = "B", signaling = "CLEC")

rankNet(all_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = c("CD14 Monos", "CD8+ T cells", "CD4+ T cells", "NK", "B"))

rankNet(all_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = "CD14 Monos")
rankNet(all_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = "CD8+ T cells")
rankNet(all_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = "CD4+ T cells")
rankNet(all_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = "NK")
rankNet(all_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = "B")



```


```{r}
# Titles do not output

netVisual_diffInteraction(tet2_merged_cc, title.name = "TET2 CD14+ Monocytes Outgoing Differential Signaling", weight.scale = T, measure = "weight", sources.use = c("CD14+ Monocytes"), targets.use = c("CD8+ T cells", "CD4+ T cells", "B cells", "NK cells", "CD16+ Monocytes", "Dendritic cells", "Erythroid-like cells", "Platelets"), color.use = rep("grey", 9), color.edge = brewer.pal(4, "Paired")[c(4,2)])
netVisual_diffInteraction(dnmt3a_merged_cc, title.name = "DNMT3A CD14+ Monocytes Outgoing Differential Signaling",weight.scale = T, measure = "weight", sources.use = c("CD14+ Monocytes"), targets.use = c("CD8+ T cells", "CD4+ T cells", "B cells", "NK cells", "CD16+ Monocytes", "Dendritic cells", "Erythroid-like cells", "Platelets"), color.use = rep("grey", 9), color.edge = brewer.pal(4, "Paired")[c(4,2)])

netVisual_diffInteraction(tet2_merged_cc, title.name = "TET2 CD4+ T Cells Outgoing Differential Signaling", weight.scale = T, measure = "weight", sources.use = c("CD4+ T cells"), targets.use = c("CD8+ T cells", "CD14+ Monocytes", "B cells", "NK cells", "CD16+ Monocytes", "Dendritic cells", "Erythroid-like cells", "Platelets"), color.use = rep("grey", 9), color.edge = brewer.pal(4, "Paired")[c(4,2)])
netVisual_diffInteraction(dnmt3a_merged_cc, title.name = "DNMT3A CD4+ T Cells Outgoing Differential Signaling", weight.scale = T, measure = "weight", sources.use = c("CD4+ T cells"), targets.use = c("CD8+ T cells", "CD14+ Monocytes", "B cells", "NK cells", "CD16+ Monocytes", "Dendritic cells", "Erythroid-like cells", "Platelets"), color.use = rep("grey", 9), color.edge = brewer.pal(4, "Paired")[c(4,2)])

```



# Objects created by Brett, separated by stim status.
```{r}
system("gsutil cp -r gs://fc-secure-0a0db300-cd6b-49a0-a17e-633b998bfc65/CH_Multiomics/seurat_objects/cellchat rds_objects/" )
```

```{r}
tet2_veh_cc = readRDS("rds_objects/cellchat/cellchat_unstim_tet.rds")
tet2_stim_cc = readRDS("rds_objects/cellchat/cellchat_stim_tet.rds")
dnmt3a_veh_cc = readRDS("rds_objects/cellchat/cellchat_unstim_dnmt.rds")
dnmt3a_stim_cc = readRDS("rds_objects/cellchat/cellchat_stim_dnmt.rds")
control_veh_cc = readRDS("rds_objects/cellchat/cellchat_unstim_control.rds")
control_stim_cc = readRDS("rds_objects/cellchat/cellchat_stim_control.rds")

```


```{r}
tet2_veh_cc.list = list(TET2 = tet2_veh_cc, Control = control_veh_cc)
tet2_veh_merged_cc = mergeCellChat(tet2_veh_cc.list, add.names = names(tet2_veh_cc.list))
tet2_veh_merged_cc = updateCellChat(tet2_veh_merged_cc)

dnmt3a_veh_cc.list = list(DNMT3A = dnmt3a_veh_cc, Control = control_veh_cc)
dnmt3a_veh_merged_cc = mergeCellChat(dnmt3a_veh_cc.list, add.names = names(dnmt3a_veh_cc.list))
dnmt3a_veh_merged_cc = updateCellChat(dnmt3a_veh_merged_cc)

all_veh_cc.list = list(TET2 = tet2_veh_cc, DNMT3A = dnmt3a_veh_cc, Control = control_veh_cc)
all_veh_merged_cc = mergeCellChat(all_veh_cc.list, add.names = names(all_veh_cc.list))
all_veh_merged_cc = updateCellChat(all_veh_merged_cc)

tet2_stim_cc.list = list(TET2 = tet2_stim_cc, Control = control_stim_cc)
tet2_stim_merged_cc = mergeCellChat(tet2_stim_cc.list, add.names = names(tet2_stim_cc.list))
tet2_stim_merged_cc = updateCellChat(tet2_stim_merged_cc)

dnmt3a_stim_cc.list = list(DNMT3A = dnmt3a_stim_cc, Control = control_stim_cc)
dnmt3a_stim_merged_cc = mergeCellChat(dnmt3a_stim_cc.list, add.names = names(dnmt3a_stim_cc.list))
dnmt3a_stim_merged_cc = updateCellChat(dnmt3a_stim_merged_cc)

all_stim_cc.list = list(TET2 = tet2_stim_cc, DNMT3A = dnmt3a_stim_cc, Control = control_stim_cc)
all_stim_merged_cc = mergeCellChat(all_stim_cc.list, add.names = names(all_stim_cc.list))
all_stim_merged_cc = updateCellChat(all_stim_merged_cc)
```

```{r}
rankNet(all_veh_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = "CD8+ T cells")
rankNet(all_veh_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = "CD4+ T cells")
rankNet(all_veh_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = "NK")
rankNet(all_veh_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = "B")


rankNet(all_stim_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = "CD14 Monos")
rankNet(all_stim_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = "CD8+ T cells")
rankNet(all_stim_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = "CD4+ T cells")
rankNet(all_stim_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = "NK")
rankNet(all_stim_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = "B")
```


```{r}


tet2_cd4_veh_merged_cc_plot = rankNet(tet2_veh_merged_cc, mode = "comparison", comparison = c(1,2), sources.use = "CD4+ T cells", signaling = c("CD99", "MIF"), color.use = brewer.pal(12, "Paired")[c(4,2)])
dnmt3a_cd4_veh_merged_cc_plot = rankNet(dnmt3a_veh_merged_cc, mode = "comparison", comparison = c(1,2), sources.use = "CD4+ T cells", signaling = c("ADGRE5", "MIF"), color.use = brewer.pal(12, "Paired")[c(6,2)])

save_plot(tet2_cd4_veh_merged_cc_plot, "figures/cellchat/tet2_cd4_veh_cellchat_bar", width = 6)
save_plot(dnmt3a_cd4_veh_merged_cc_plot, "figures/cellchat/dnmt3a_cd4_veh_cellchat_bar", width = 6)


cd14_cc_data_tet2 = rankNet(all_veh_merged_cc, mode = "comparison", comparison = c(1,3), sources.use = "CD14 Monos", signaling = c("GALECTIN", "MIF", "THBS"), return.data = TRUE, do.stat = TRUE)
cd14_cc_data_dnmt3a = rankNet(all_veh_merged_cc, mode = "comparison", comparison = c(2,3), sources.use = "CD14 Monos", signaling = c("GALECTIN", "MIF", "THBS"), return.data = TRUE, do.stat = TRUE)
(cd14_cc_plot = rankNet(all_veh_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = "CD14 Monos", signaling = c("GALECTIN", "MIF", "THBS"), return.data = TRUE, do.stat = TRUE, color.use = brewer.pal(12, "Paired")[c(4,6,2)]))

cd14_cc_data = rbind(cd14_cc_data_tet2$signaling.contribution, cd14_cc_data_dnmt3a$signaling.contribution) %>% as.data.frame()
write_tsv(cd14_cc_data, "tables/cellchat/cd14_veh_cc_data.tsv")
save_plot(cd14_cc_plot$gg.obj, "figures/cellchat/cd14_cc_bar")


cd4_cc_data_tet2 = rankNet(all_veh_merged_cc, mode = "comparison", comparison = c(1,3), sources.use = "CD4+ T cells", signaling = c("CD45", "ADGRE5", "CD99"), return.data = TRUE, do.stat = TRUE)
cd4_cc_data_dnmt3a = rankNet(all_veh_merged_cc, mode = "comparison", comparison = c(2,3), sources.use = "CD4+ T cells", signaling = c("CD45", "ADGRE5", "CD99"), return.data = TRUE, do.stat = TRUE)
(cd4_cc_plot = rankNet(all_veh_merged_cc, mode = "comparison", comparison = c(1,2,3), sources.use = "CD4+ T cells", signaling = c("CD45", "ADGRE5", "CD99"), return.data = TRUE, do.stat = TRUE, color.use = brewer.pal(12, "Paired")[c(4,6,2)]))

cd4_cc_data = rbind(cd4_cc_data_tet2$signaling.contribution, cd4_cc_data_dnmt3a$signaling.contribution) %>% as.data.frame()
write_tsv(cd4_cc_data, "tables/cellchat/cd4_veh_cc_data.tsv")
save_plot(cd4_cc_plot$gg.obj, "figures/cellchat/cd4_cc_bar")

```

```{r}
tet2_cd14_stim_merged_cc_plot = rankNet(tet2_stim_merged_cc, mode = "comparison", comparison = c(1,2), sources.use = "CD14 Monos", signaling = c("IL6", "ADGRE5", "CLEC"), color.use = brewer.pal(12, "Paired")[c(4,2)])
dnmt3a_cd14_stim_merged_cc_plot = rankNet(dnmt3a_stim_merged_cc, mode = "comparison", comparison = c(1,2), sources.use = "CD14 Monos", signaling = c("IL6", "ADGRE5", "CLEC"), color.use = brewer.pal(12, "Paired")[c(6,2)])

save_plot(tet2_cd14_stim_merged_cc_plot, "figures/cellchat/tet2_cd14_stim_cellchat_bar", width = 6)
save_plot(dnmt3a_cd14_stim_merged_cc_plot, "figures/cellchat/dnmt3a_cd14_stim_cellchat_bar", width = 6)


```

