---
title: "codex"
output: html_document
date: '2023-03-30'
---

# Set up.
```{r setup, include = FALSE, out.height="50%"}
knitr::opts_knit$set(root.dir = "~/Alyssa/Single_Cell_CHIP/")

library(Seurat)
library(tidyverse)
```

```{r}
make_akoya_seurat = function(path_to_data) {
  mtx = data.table::fread(
    file = path_to_data,
    sep = '\t',
    data.table = FALSE,
    verbose = FALSE
  )
  
  # Create centroids
  xpos = sort(
    grep(pattern = 'Centroid X', colnames(mtx), value = TRUE),
    decreasing = TRUE
  )[1]
  ypos = sort(
    grep(pattern = 'Centroid Y', colnames(mtx), value = TRUE),
    decreasing = TRUE
  )[1]
  centroids = data.frame(
    x = mtx[[xpos]],
    y = mtx[[ypos]],
    cell = rownames(mtx),
    stringsAsFactors = FALSE
  )
  # Create metadata
  cols = setdiff(
    grep(
      pattern = 'Cell: .+mean',
      x = colnames(mtx),
      ignore.case = TRUE,
      value = TRUE,
      invert = TRUE
    ),
    y = c(xpos, ypos)
  )
  md = mtx[, cols, drop = FALSE]
  # Create expression matrix
  idx = which(grepl(
    pattern = 'Cell: .+mean',
    x = colnames(mtx),
    ignore.case = TRUE
  ))
  mtx = mtx[, idx, drop = FALSE]
  colnames(mtx) = vapply(
    X = strsplit(colnames(mtx), split = ':'),
    FUN = '[[',
    FUN.VALUE = character(length = 1),
    2
  )
  colnames(mtx) = vapply(
    X = strsplit(colnames(mtx), split = ' '),
    FUN = '[[',
    FUN.VALUE = character(length = 1),
    2L
  )
  mtx = t(mtx)
  assay = "Akoya"
  coords =CreateFOV(
    coords = centroids,
    type = 'centroids',
    key = 'fov',
    assay = assay
  )
  colnames(md) = make.names(names = colnames(md))
  colnames(mtx) = paste0("Cell_", 1:ncol(mtx))
  coords@boundaries$centroids@cells = paste0("Cell_", 1:ncol(mtx))
  
  # build Seurat object from matrix
  obj = CreateSeuratObject(
    counts = mtx,
    assay = assay,
    meta.data = md
  )
  # make sure coords only contain cells in seurat object
  coords = subset(coords, cells = Cells(obj))
  obj[["fov"]] = coords # add image to seurat object
  # Add additional assays
  for (i in setdiff(names(data), y = c('matrix', 'centroids', 'metadata'))) {
    obj[[i]] = CreateAssayObject(counts = data[[i]])
  }
  return(obj)
}
```

```{r}
obj = make_akoya_seurat("input_data/qupath/matrix_measurements_20230308-BM_H22-1362.txt")
obj_2 = make_akoya_seurat("input_data/qupath/matrix_measurements_20230306-BM_H20-3706.txt")
```

```{r}
process_codex_seurat = function(codex_obj) {
  codex_obj = NormalizeData(codex_obj, normalization.method = "CLR", margin = 2)
  codex_obj = ScaleData(codex_obj)
  VariableFeatures(codex_obj) = rownames(codex_obj)  # since the panel is small, treat all features as variable.
  codex_obj = RunPCA(object = codex_obj, npcs = 10, verbose = FALSE, approx = FALSE)
  codex_obj = RunUMAP(object = codex_obj, dims = 1:10, verbose = FALSE)
  codex_obj = FindNeighbors(object = codex_obj, dims = 1:10, verbose = FALSE)
  codex_obj = FindClusters(object = codex_obj, verbose = FALSE, resolution = 0.4, n.start = 1)
}
```

```{r}
codex_obj = process_codex_seurat(obj)
codex_obj_2 = process_codex_seurat(obj_2)
```

```{r}
DimPlot(codex_obj, label = TRUE, label.box = TRUE) + NoLegend()
DimPlot(codex_obj_2, label = TRUE, label.box = TRUE) + NoLegend()
```

```{r}
ImageDimPlot(codex_obj, cols = "parade")
ImageDimPlot(codex_obj_2, cols = "parade")
```

```{r}
for (obj in c(codex_obj, codex_obj_2)) {
  p1 = ImageFeaturePlot(obj, features = c("CD3e", "CD8", "CD45"),
    min.cutoff = "q10", max.cutoff = "q90", axes = TRUE)
  p2 = ImageDimPlot(obj, cols = "parade")
  print(p1 + p2)
}
```

```{r}
for (obj in c(codex_obj, codex_obj_2)) {
  p1 = ImageFeaturePlot(obj, features = c("CD20", "CDH1", "CD45"),
    min.cutoff = "q10", max.cutoff = "q90")
  p2 = ImageDimPlot(obj, cols = "parade")
  print(p1 + p2)
}
```

```{r}
for (obj in c(codex_obj, codex_obj_2)) {
  cropped_coords = Crop(obj[["fov"]], x = c(0, 8000), y = c(2500, 6500), coords = "plot")
  obj[["zoom"]] = cropped_coords
  # visualize cropped area with cell segmentations & selected molecules

  p1 = ImageFeaturePlot(obj, fov = "zoom", features = c("CD20", "CDH1", "CD45"),
    min.cutoff = "q10", max.cutoff = "q90")
  p2 = ImageDimPlot(obj, fov = "zoom", cols = "parade", coord.fixed = FALSE)
  print(p1 + p2)
}
```

```{r}
for (obj in c(codex_obj, codex_obj_2)) {
  cropped_coords = Crop(obj[["fov"]], x = c(4500, 6500), y = c(3000, 4500), coords = "plot")
  obj[["zoom"]] = cropped_coords
  # visualize cropped area with cell segmentations & selected molecules

  p1 = ImageFeaturePlot(obj, fov = "zoom", features = c("CD20", "CDH1", "CD45"),
    min.cutoff = "q10", max.cutoff = "q90")
  p2 = ImageDimPlot(obj, fov = "zoom", cols = "parade", coord.fixed = FALSE)
  print(p1 + p2)
}
```
# Get defining markers for each cluster to label which ident is which cell type.
```{r}
codex_cluster_markers = FindAllMarkers(codex_obj, only.pos = TRUE)
codex_cluster_markers_2 = FindAllMarkers(codex_obj_2, only.pos = TRUE)

```

```{r}
saveRDS(codex_obj, "rds_objects/codex/codex_obj.rds")
saveRDS(codex_obj_2, "rds_objects/codex/codex_obj_2.rds")

```

```{r}
codex_obj = readRDS("rds_objects/codex/codex_obj.rds")
```

```{r}
for(obj in c(codex_obj, codex_obj_2)) {
  cropped_coords = Crop(obj[["fov"]], x = c(4750, 6000), y = c(3250, 4000), coords = "plot")
  obj[["zoom"]] = cropped_coords
  # visualize cropped area with cell segmentations & selected molecules

  p1 = ImageFeaturePlot(obj, fov = "zoom", features = c("CD20", "CDH1", "CD45"),
    min.cutoff = "q10", max.cutoff = "q90")
  p2 = ImageDimPlot(obj, fov = "zoom", cols = "parade", coord.fixed = FALSE)
  print(p1 + p2)
}
```
```{r}
cropped_coords = Crop(codex_obj[["fov"]], x = c(0, 8000), y = c(2500, 6500), coords = "plot")
codex_obj[["zoom"]] = cropped_coords

codex_obj$cell_type = "placeholder"
codex_obj$cell_type[codex_obj$seurat_clusters == 0] = "Lumen"
codex_obj$cell_type[codex_obj$seurat_clusters == 1] = "T cell"
codex_obj$cell_type[codex_obj$seurat_clusters == 2] = "Monocyte"
codex_obj$cell_type[codex_obj$seurat_clusters == 3] = "Proliferating"
codex_obj$cell_type[codex_obj$seurat_clusters == 4] = "Endothelial"
codex_obj$cell_type[codex_obj$seurat_clusters == 5] = "T cell"
codex_obj$cell_type[codex_obj$seurat_clusters == 6] = "T cell"
codex_obj$cell_type[codex_obj$seurat_clusters == 7] = "Endothelial"
codex_obj$cell_type[codex_obj$seurat_clusters == 8] = "Other"
codex_obj$cell_type[codex_obj$seurat_clusters == 9] = "B cell"
codex_obj$cell_type[codex_obj$seurat_clusters == 10] = "T cell"
codex_obj$cell_type[codex_obj$seurat_clusters == 11] = "Lumen"
codex_obj$cell_type = factor(codex_obj$cell_type, levels = c("Monocyte", "T cell", "B cell", "Endothelial", "Lumen", "Proliferating", "Other"))

Idents(codex_obj) = "cell_type"
p2 = ImageDimPlot(codex_obj, fov = "zoom", cols = "parade", coord.fixed = FALSE)
p2
```

```{r}
cropped_coords = Crop(codex_obj[["fov"]], x = c(6000, 8000), y = c(2500, 3500), coords = "plot")
codex_obj[["zoom"]] = cropped_coords

(p2 = ImageDimPlot(codex_obj, fov = "zoom", cols = "parade", coord.fixed = FALSE) +
  theme(legend.text = element_text(size = 25),
        legend.title = element_blank()))

```

```{r}
cropped_coords = Crop(codex_obj[["fov"]], x = c(7000, 7500), y = c(2750, 3250), coords = "plot")
codex_obj[["zoom"]] = cropped_coords

(p3 = ImageDimPlot(codex_obj, fov = "zoom", cols = "parade", coord.fixed = FALSE, alpha = 0.5) +
  theme(legend.text = element_text(size = 25),
        legend.title = element_blank()))

```

