---
title: "parse_mutated_wt"
output: html_document
date: "2023-05-01"
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/Alyssa/Single_Cell_CHIP/")

library(Seurat)
library(tidyverse)

source("../scripts/image_formatting.R")
```


```{r}
system("gsutil cp 'gs://fc-secure-0a0db300-cd6b-49a0-a17e-633b998bfc65/Rstudio_files/Maester_objects/afmatrix_033.txt' input_data/ ")
system("gsutil cp 'gs://fc-secure-0a0db300-cd6b-49a0-a17e-633b998bfc65/CH_Multiomics/maester/CH_21_046/afmatrix_046.txt' input_data/")
system("gsutil cp 'gs://fc-secure-0a0db300-cd6b-49a0-a17e-633b998bfc65/CH_Multiomics/maester/CH_21_046/afmatrix_046.txt' input_data/")
```

```{r}
mut_wt_matrix = read.table("input_data/afmatrix_046.txt")
seurat_046 = readRDS("rds_objects/DNMT3Amutant_seu.rds")
```

```{r}
FREQ_CUTOFF = 0.03
variant_sum = rowSums(mut_wt_matrix)
variant_non_zero = apply(mut_wt_matrix, 1, function(x) sum(x != 0))
informative_matrix = mut_wt_matrix[which(variant_non_zero > FREQ_CUTOFF * ncol(mut_wt_matrix)),]

```

```{r}
# This would take a very long time to run - instead 1) subset and 2) use fastcluster.
# dist_matrix = dist(informative_matrix)
# hclust_result = hclust(informative_matrix)
```

# Hierachical clustering not ideal for large datasets. Kmeans better suited but not informative for what we need.
```{r}
# #install.packages("factoextra")
# library(factoextra)
# (plot = fviz_nbclust(informative_matrix, kmeans))
# 
# save_plot(plot, "figures/kmeans_elbow_plot")
# set.seed(123)
# km_res = kmeans(informative_matrix, 7, nstart = 25)
```

```{r}
library(fastcluster)
library(dendextend)

normalized_matrix = NormalizeData(informative_matrix)
informative_matrix[informative_matrix < 5] = 0
informative_matrix[informative_matrix > 0] = 1


dist_matrix = dist(normalized_matrix[c(which(rownames(normalized_matrix) %in% c("747_A>G", "2781_T>C", "15549_T>C")), sample(1:nrow(normalized_matrix), 10)),])
#dist_matrix = dist(normalized_matrix)
hclust_result = hclust(dist_matrix)

pdf("figures/hclust_plot.pdf", width = 60)
as.dendrogram(hclust_result) %>% 
  set("by_labels_branches_col", value = seurat_046@meta.data$Cell_ID[seurat_046@meta.data$CLONE == "Mutant"] %>% na.omit()) %>% 
  plot()
dev.off()

heatmap(dist_matrix %>% as.matrix())


label_dist_matrix = dist(informative_matrix)
(label_heatmap = Heatmap(label_dist_matrix %>% as.matrix()))

```
```{r}
interesting_rows = informative_matrix[c("747_A>G", "2781_T>C", "15549_T>C"),] %>%
  t() %>%
  as.data.frame()
table(interesting_rows$`747_A>G`, interesting_rows$`2781_T>C`, interesting_rows$`15549_T>C`)
table(interesting_rows)

```

```{r}
# pdf("figures/hclust_plot.pdf", width = 50, height = 20)
# plot(x = hclust_result, labels =  row.names(hclust_result), cex = 0.5)
# dev.off()

colnames(informative_matrix) = paste0("046_", gsub("\\.", "-", colnames(informative_matrix)))
mono_data = informative_matrix[,intersect(colnames(informative_matrix), intersect(seurat_046@meta.data$Cell_ID[!is.na(seurat_046@meta.data$CLONE)], seurat_046@meta.data$Cell_ID[seurat_046@meta.data$cell_type == "CD14 Monos"]))]
t_dist_matrix = dist(t(mono_data)) #[,sample(1:ncol(mono_data), 500)]
t_hclust_result = hclust(t_dist_matrix)


(heatmap = heatmap(normalized_matrix %>% as.matrix()))

library(ComplexHeatmap)
colnames(normalized_matrix) = paste0("046_", gsub("\\.", "-", colnames(normalized_matrix)))
(heatmap = Heatmap(normalized_matrix[,] %>% as.matrix())) #c(which(rownames(normalized_matrix) == "7754_G>C"), sample(1:nrow(normalized_matrix), 50))

labRow = rownames(normalized_matrix) == "7754_G>C"
labRow[labRow == FALSE] = ""
labRow[labRow == TRUE] = "7754_G>C"

(label_heatmap = Heatmap(normalized_matrix %>% as.matrix(), row_labels = labRow))
(label_heatmap = Heatmap(normalized_matrix %>% as.matrix()))


pdf("figures/hclust_plot_t.pdf", width = 50)
as.dendrogram(t_hclust_result) %>% 
  set("by_labels_branches_col", value = seurat_046@meta.data$Cell_ID[seurat_046@meta.data$CLONE == "Mutant"] %>% na.omit()) %>% 
  plot()
dev.off()


ggplot(normalized_matrx %>% as.data.frame())
```


```{r}
install.packages("dendextend")
library(dendextend)
#color
dend15 %>% set("by_labels_branches_col", value = c(1,4)) %>% 
   plot(main = "Adjust the branch\n if ALL (default) of its\n labels are in the list")
dend15 %>% set("by_labels_branches_col", value = c(1,4), type = "any") %>% 
   plot(main = "Adjust the branch\n if ANY of its\n labels are in the list")
#color with palette
library(viridis)
par(mfrow = c(1,3))
dend %>% highlight_branches_col %>% plot(main = "Coloring branches \n (default is reversed viridis)")
#collapse sparse branches i think?
dend %>% collapse_branch(tol = 0.2) %>% ladderize %>% plot(horiz = TRUE)
dend %>% collapse_branch(tol = 0.2) %>% ladderize %>% hang.dendrogram(hang = 0) %>% plot(horiz = TRUE)
```

```{r}

test_dist_matrix = dist(test_matrix[1:100,1:100])
test_hclust_result = hclust(test_dist_matrix)

as.dendrogram(test_hclust_result) %>% collapse_branch(tol = 0.2) %>% ladderize %>% plot(horiz = TRUE)

highlight_branches_col %>% plot()
```

```{r}
saveRDS(hclust_result, "rds_objects/hclust_result.rds")
```

