---
title: "Additional calculations for manuscript"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/Alyssa/Single_Cell_CHIP/")

library(tidyverse)
library(Seurat)
```

# Number of control cells.
```{r}
diet_seurat_trimmed = readRDS("rds_objects/diet_seurat_trimmed.rds")

summarize_data = function(data, grouping_category) {
  ignore_cells = c()
  summary_stats = data@meta.data %>%
    dplyr::group_by(across(all_of(grouping_category)), cell_type) %>%
    dplyr::summarize(count = dplyr::n()) %>%
    dplyr::mutate(cell_type = factor(cell_type, levels = c("CD4+ T cells", "CD8+ T cells", "CD14+ Monocytes", "NK cells", "B cells", "CD16+ Monocytes", "Dendritic cells",  "Erythroid-like cells", "Platelets"))) %>%
    dplyr::arrange(cell_type) %>%
    na.omit() %>%
    tidyr::pivot_wider(names_from = cell_type, values_from = count)
  return(summary_stats)
}

summarized_data = summarize_data(diet_seurat_trimmed, "MUTATION.GROUP")
rowSums(summarized_data[,2:6])
```

# Number of mutated cells and nonmutated cells.
```{r}
clone_data = readRDS("rds_objects/seurat_with_clones_5.11.23.rds")

clone_data@meta.data$cell_type[clone_data@meta.data$cell_type == "CD14 Monos"] = "CD14+ Monocytes"
clone_data@meta.data$cell_type[clone_data@meta.data$cell_type == "CD16 Monos"] = "CD16+ Monocytes"
clone_data@meta.data$cell_type[clone_data@meta.data$cell_type == "B"] = "B cells"
clone_data@meta.data$cell_type[clone_data@meta.data$cell_type == "NK"] = "NK cells"

clone_data_for_radar = clone_data@meta.data %>%
  filter(!(MUTATION.GROUP %in% c("TET2", "DNMT3A") & is.na(Clone))) %>%
  dplyr::select(cell_type, MUTATION.GROUP, Clone) %>%
  group_by(MUTATION.GROUP, Clone) %>%
  summarise(count = n())

```

# Statistical test for cell type proportions in aggregated cell types.
```{r}
library(scProportionTest)

prop_test = sc_utils(diet_seurat_trimmed)
prop_test@meta_data = prop_test@meta_data %>%
  mutate(MUTATION.GROUP = as.factor(diet_seurat_trimmed$MUTATION.GROUP %>% unlist())) %>%
  mutate(cell_type = as.factor(diet_seurat_trimmed$cell_type))

prop_test_tet2 = permutation_test(
  prop_test, cluster_identity = "cell_type",
  sample_1 = "none", sample_2 = "TET2",
  sample_identity = "MUTATION.GROUP"
)
permutation_plot(prop_test_tet2)

prop_test_dnmt3a = permutation_test(
  prop_test, cluster_identity = "cell_type",
  sample_1 = "none", sample_2 = "DNMT3A",
  sample_identity = "MUTATION.GROUP"
)
permutation_plot(prop_test_dnmt3a)
```
# Statistical test for cell type proportions in mutant and wildtype cells.
```{r}
library(scProportionTest)

clone_data = readRDS("../SC_CHIP_HIV_Diabetes/input_data/seurat_with_clones_PB_10.16.23.rds")
clone_data_014 = clone_data %>% subset(CHIVEID == "CH-21-014")

prop_test = sc_utils(clone_data_014)
prop_test@meta_data = prop_test@meta_data %>%
  mutate(Clone = as.factor(clone_data_014$Clone %>% unlist())) %>%
  mutate(cell_type = as.factor(clone_data_014$cell_type))

prop_test_tet2 = permutation_test(
  prop_test, cluster_identity = "cell_type",
  sample_1 = "Wildtype", sample_2 = "Mutant",
  sample_identity = "Clone"
)
permutation_plot(prop_test_tet2)

```

