
---
title: "compare_to_nam"
output: html_document
---

```{r setup}
knitr::opts_knit$set(root.dir = "~/Alyssa/Single_Cell_CHIP/")
library(tidyverse)
```

```{r}
pawan_results = read_csv("tables/pooled_mutant_vs_control_10_20_23/DNMT3A CD14 Mutant vs Control.csv")
nam_results = readxl::read_excel("input_data/41588_2022_1179_MOESM3_ESM.xlsx", sheet = "Table 3")[3:2013,37:40]

colnames(nam_results) = nam_results[1,]
nam_results = nam_results[2:2011,]
```

```{r}
nam_pos = nam_results %>%
  mutate(`P-value (Permutation Test)` = as.double(`P-value (Permutation Test)`)) %>%
  filter(`P-value (Permutation Test)` < 0.05 & `Mean log(Fold-change)` > 0) %>%
  pull(Gene)

nam_neg = nam_results %>%
  mutate(`P-value (Permutation Test)` = as.double(`P-value (Permutation Test)`)) %>%
  filter(`P-value (Permutation Test)` < 0.05 & `Mean log(Fold-change)` < 0) %>%
  pull(Gene)
```

```{r}
pawan_pos = pawan_results %>%
  filter(fdr < 0.05 & coef > 0) %>%
  pull(primerid)

pawan_neg = pawan_results %>%
  filter(fdr < 0.05 & coef < 0) %>%
  pull(primerid)
```

```{r}
length(nam_pos)
length(pawan_pos)
length(intersect(nam_pos, pawan_pos))

length(nam_neg)
length(pawan_neg)
length(intersect(nam_neg, pawan_neg))
```

```{r}
length(intersect(nam_results$Gene, pawan_results$primerid))
length(intersect(nam_results$Gene, c(pawan_pos, pawan_neg)))
length(intersect(c(nam_pos, nam_neg), pawan_results$primerid))

```

```{r}
intersect(nam_pos, pawan_pos)
intersect(nam_neg, pawan_neg)
intersect(c(nam_pos, nam_neg), pawan_results$primerid)
```

