---
title: "metacell"
output: html_document
date: '2023-04-10'
---

```{r setup}
knitr::opts_knit$set(root.dir = "~/Alyssa/Single_Cell_CHIP/")

library(tidyverse)
library(Seurat)
library(DropletUtils)
library(Matrix)
```

# Trim excessive data and clear remaining doublets.
```{r}
#diet_seurat = DietSeurat(scaled_filtered_annotated_seurat, assays = "RNA")
#saveRDS(diet_seurat, "rds_objects/diet_seurat.rds")

# need some more stringent removal of doublets for one lane
pANN_frame = read_tsv("input_data/pANN_frame.tsv") %>% as.data.frame()
rownames(pANN_frame) = pANN_frame$cell_ID
diet_seurat_trimmed = AddMetaData(diet_seurat, pANN_frame)

cells_to_remove = diet_seurat_trimmed@meta.data %>%
  filter(LANE == "7079-3") %>%
  filter(pANN >= 0.28) %>%
  pull(cell_ID)

diet_seurat_trimmed = diet_seurat_trimmed[,!colnames(diet_seurat_trimmed) %in% cells_to_remove]
saveRDS(diet_seurat_trimmed, "rds_objects/diet_seurat_trimmed.rds")

```

```{r}
# save files (followed explanation here: https://www.biomage.net/blog/how-to-demultiplex-a-seurat-object-and-convert-it-to-10x-files)
diet_seurat_trimmed = readRDS("rds_objects/diet_seurat_trimmed.rds")

DefaultAssay(diet_seurat_trimmed) <- "RNA"
counts = diet_seurat_trimmed[["RNA"]]@data

demultiplex_convert_to_10x = function(obj, samples) { 
    for (i in 1:length(samples)) {
      print(paste0("Converting sample ", samples[i]))
      obj.sub = obj[[samples[i]]]
      DropletUtils::write10xCounts(path = paste0(getwd(),"/demultiplexed_cell_types/",samples[i]), x = obj.sub[["RNA"]]@data, type = "sparse", version="3")
      }
}



```


# Split and save by CHIP/control.
```{r}
diet_seurat_trimmed@meta.data$Cell_Type_Group = paste(diet_seurat_trimmed@meta.data$cell_type, diet_seurat_trimmed@meta.data$GROUP)
diet_seurat_trimmed.list = Seurat::SplitObject(diet_seurat_trimmed, split.by = "Cell_Type_Group")
sample.names = unique(diet_seurat_trimmed$Cell_Type_Group)

demultiplex_convert_to_10x(obj = diet_seurat_trimmed.list, samples = sample.names)

```


# Split and save by TET2/SRSF2 and TET2.
```{r}
diet_seurat_trimmed = readRDS("rds_objects/diet_seurat_trimmed.rds")

DefaultAssay(diet_seurat_trimmed) = "RNA"
counts = diet_seurat_trimmed[["RNA"]]@data

demultiplex_convert_to_10x = function(obj, samples) { 
    for (i in 1:length(samples)) {
      print(paste0("Converting sample ", samples[i]))
      obj.sub = obj[[samples[i]]]
      DropletUtils::write10xCounts(path = paste0(getwd(),"/demultiplexed_cell_types_revision/",samples[i]), x = obj.sub[["RNA"]]@data, type = "sparse", version="3")
      }
}

revision_seurat = subset(diet_seurat_trimmed, subset = MUTATION.GROUP == "TET2")
revision_seurat$MUTATION.SUBGROUP = "placeholder"
revision_seurat$MUTATION.SUBGROUP[revision_seurat$MUTATION %in% c("TET2 V1900F (2%)", "TET2 G68X (2%)", "TET2 (33%)", "TET2 (6.2%)", "TET2 C1378Y (23%)")] = "TET2"
revision_seurat$MUTATION.SUBGROUP[revision_seurat$MUTATION %in% c("TET2 R1516X (30%), TET2 Q659X (29%), SRSF2 P95H (3%)", "SRSF2 P95R (40%), TET2 L957Ifs*15 (51%)", "SRSF2 (33%), TET2 Y1245Lfs*22 (27%), TET2 Q742X(42%)")] = "TET2_SRSF2"
revision_seurat$Cell_Type_Group = paste(revision_seurat$cell_type, revision_seurat$MUTATION.SUBGROUP, revision_seurat$STIM)

revision_seurat = subset(revision_seurat, subset = cell_type == "CD14 Monos")

revision_seurat.list = Seurat::SplitObject(revision_seurat, split.by = "Cell_Type_Group")
sample.names = unique(revision_seurat$Cell_Type_Group)

demultiplex_convert_to_10x(obj = revision_seurat.list, samples = sample.names)

```

# Split and save by CHIP/CCUS/control and cell types.
```{r}
# Function for demultiplexing and saving in CCUS folder.
demultiplex_convert_to_10x = function(obj, samples) { 
    if(!dir.exists(file.path(getwd(), "ccus_demultiplexed"))) {
      dir.create(file.path(getwd(), "ccus_demultiplexed"))
    }
    for (i in 1:length(samples)) {
      print(paste0("Converting sample ", samples[i]))
      obj.sub = obj[[samples[i]]]
      DropletUtils::write10xCounts(path = paste0(getwd(),"/ccus_demultiplexed_cell_types/",samples[i]), x = obj.sub[["RNA"]]@data, type = "sparse", version="3")
      }
}

# Add CCUS labels.
diet_seurat_trimmed@meta.data$CCUS = "Control"
diet_seurat_trimmed@meta.data$CCUS[diet_seurat_trimmed@meta.data$CHIP == "chip"] = "CHIP"
diet_seurat_trimmed@meta.data$CCUS[diet_seurat_trimmed@meta.data$CHIVEID %in% c("CH-20-004", "CH-21-014", "CH-21-073")] = "CCUS"

# Create CCUS cell type group labels.
diet_seurat_trimmed@meta.data$Cell_Type_Group = paste(diet_seurat_trimmed@meta.data$cell_type, diet_seurat_trimmed@meta.data$MUTATION.GROUP, diet_seurat_trimmed@meta.data$CCUS, diet_seurat_trimmed@meta.data$STIM, sep = "_")

# Split and save.
diet_seurat_trimmed.list = Seurat::SplitObject(diet_seurat_trimmed, split.by = "Cell_Type_Group")
sample.names = names(diet_seurat_trimmed.list)
rm(diet_seurat_trimmed)
gc()
demultiplex_convert_to_10x(obj = diet_seurat_trimmed.list, samples = sample.names)
```

