---
title: "generate_plots"
output: html_document
date: '2023-03-22'
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/Alyssa/Single_Cell_CHIP/")

library(Seurat)
library(tidyverse)

output_dir = "figures/"

source("../scripts/image_formatting.R")
```

```{r}
scaled_filtered_annotated_seurat = readRDS("rds_objects/scaled_filtered_annotated_seurat.rds")
diet_seurat_trimmed = readRDS("rds_objects/diet_seurat_trimmed.rds")

diet_seurat_trimmed@meta.data$cell_type[diet_seurat_trimmed@meta.data$cell_type == "CD14 Monos"] = "CD14+ Monocytes"
diet_seurat_trimmed@meta.data$cell_type[diet_seurat_trimmed@meta.data$cell_type == "CD16 Monos"] = "CD16+ Monocytes"
diet_seurat_trimmed@meta.data$cell_type[diet_seurat_trimmed@meta.data$cell_type == "B"] = "B cells"
diet_seurat_trimmed@meta.data$cell_type[diet_seurat_trimmed@meta.data$cell_type == "NK"] = "NK cells"

diet_seurat_trimmed@meta.data$MUTATION.GROUP[diet_seurat_trimmed@meta.data$MUTATION.GROUP == "none"] = "Control"

```

# Plot UMAP.
```{r}
control_count = 0
dnmt3a_count = 0
tet2_count = 0

get_vaf = function(mutation, group) {
  results = str_extract_all(mutation, paste0(group, "[^)]*\\)"))
  percent_vector = lapply(results, str_extract_all, pattern = "(?<=\\().*%") %>% unlist()
  if (length(percent_vector) > 0) {
    max = substr(percent_vector, 1, nchar(percent_vector)-1) %>% as.numeric() %>% max()
    return(max)
  } else {
    return(0)
  }
}

get_vaf_identifier = function(vaf, group) {
  if (vaf > 0) {
    if (group == "DNMT3A") {
      dnmt3a_count <<- dnmt3a_count + 1 # modifies a global variable
      return(paste0(dnmt3a_count, ": ", vaf / 100))
    } else {
      tet2_count <<- tet2_count + 1 # modifies a global variable
      return(paste0(tet2_count, ": ", vaf / 100))
    }
  } else {
    control_count <<- control_count + 1 # modifies a global variable
    return(control_count)
  }
}
vaf_identifiers = diet_seurat_trimmed@meta.data %>%
  dplyr::select(CHIVEID, MUTATION, MUTATION.GROUP) %>%
  unique() %>%
  rowwise() %>%
  mutate(VAF = get_vaf(MUTATION, MUTATION.GROUP)) 
vaf_identifiers$VAF[vaf_identifiers$CHIVEID == "CH-20-001"] = 9.8
vaf_identifiers = vaf_identifiers %>%
  arrange(VAF) %>%
  mutate(vaf_identifier = paste(MUTATION.GROUP, get_vaf_identifier(VAF, MUTATION.GROUP))) %>%
  arrange(MUTATION.GROUP, vaf_identifier)
vaf_identifiers = vaf_identifiers %>%
  mutate(vaf_identifier = factor(vaf_identifier, levels = vaf_identifiers$vaf_identifier))

diet_seurat_trimmed@meta.data = diet_seurat_trimmed@meta.data %>% 
  inner_join(vaf_identifiers) %>%
  column_to_rownames("cell_ID")

(umap_patient_level_plot = ggplot(diet_seurat_trimmed@meta.data, aes(x = UMAP_1, y = UMAP_2)) +
  geom_point(aes(color = `MUTATION.GROUP`), size = 0.4) +
  facet_wrap(~vaf_identifier) +
  format_no_axes_faceted)

filename = paste0(output_dir, "umap_patient_level")
save_plot(umap_patient_level_plot, filename, height = 8, width = 8.5, png = TRUE)

```

# Plot radar.
```{r}
source("scripts/ggradar/R/ggradar.R")
source("scripts/ggradar/R/CalculateGroupPath.R")
source("scripts/ggradar/R/CalculateAxisPath.R")
source("scripts/ggradar/R/funcCircleCoords.R")



summarize_data = function(data, grouping_category) {
  ignore_cells = c()
  summary_stats = data@meta.data %>%
    dplyr::filter(!(cell_type %in% ignore_cells)) %>%
    dplyr::group_by(across(all_of(grouping_category)), cell_type) %>%
    dplyr::summarize(count = dplyr::n()) %>%
    dplyr::mutate(proportion = count / sum(count)) %>%
    dplyr::mutate(cell_type = factor(cell_type, levels = c("CD4+ T cells", "CD8+ T cells", "CD14+ Monocytes", "NK cells", "B cells", "CD16+ Monocytes", "Dendritic cells",  "Erythroid-like cells", "Platelets"))) %>%
    dplyr::arrange(cell_type) %>%
    dplyr::select(-count) %>%
    na.omit() %>%
    tidyr::pivot_wider(names_from = cell_type, values_from = proportion)
  return(summary_stats)
}

# All patients ------------------------------------------------------------
summary_stats = summarize_data(diet_seurat_trimmed, "MUTATION.GROUP")

radar_stats = summary_stats %>%
  dplyr::mutate(MUTATION.GROUP = factor(MUTATION.GROUP, levels = c("Control", "TET2", "DNMT3A")))

(radar_plot = ggradar(radar_stats, 
                values.radar = c(0, 0.2, 0.5),
                grid.min = 0, grid.mid = 0.2, grid.max = 0.5,
                group.line.width = 0.75,
                group.point.size = 1.5,
                group.colours = brewer.pal(6, "Paired")[c(2,4,6)],
                background.circle.colour = "white",
                gridline.mid.colour = "grey",
                legend.position = "bottom") +
  ggplot2::theme(plot.margin = ggplot2::margin(0, 3, 0, 3, 'cm')) +
  ggplot2::coord_cartesian(clip = "off"))

filename = paste0(output_dir, "radar_all_data")
save_plot(radar_plot, filename, height = 4, width = 6.5, png = TRUE)
write_tsv(radar_stats, "tables/radar_all_data.tsv")

```

# Plot mutant radar.
```{r}
system("gsutil cp 'gs://fc-secure-0a0db300-cd6b-49a0-a17e-633b998bfc65/CH_Multiomics/seurat_objects/seurat_with_clones_5.11.23.rds' rds_objects/")

clone_data = readRDS("rds_objects/seurat_with_clones_5.11.23.rds")

clone_data@meta.data$cell_type[clone_data@meta.data$cell_type == "CD14 Monos"] = "CD14+ Monocytes"
clone_data@meta.data$cell_type[clone_data@meta.data$cell_type == "CD16 Monos"] = "CD16+ Monocytes"
clone_data@meta.data$cell_type[clone_data@meta.data$cell_type == "B"] = "B cells"
clone_data@meta.data$cell_type[clone_data@meta.data$cell_type == "NK"] = "NK cells"

clone_data_for_radar = clone_data@meta.data %>%
  filter(!(MUTATION.GROUP %in% c("TET2", "DNMT3A") & is.na(Clone))) %>%
  dplyr::select(cell_type, MUTATION.GROUP, Clone)

clone_data_for_radar$Clone[is.na(clone_data_for_radar$Clone)] = "Control"

tet2_for_radar = clone_data_for_radar %>% filter(MUTATION.GROUP %in% c("TET2", "Control"))
dnmt3a_for_radar = clone_data_for_radar %>% filter(MUTATION.GROUP %in% c("DNMT3A", "Control"))

group_for_radar = function(data) {
  data %>%
    group_by(MUTATION.GROUP, Clone, cell_type) %>%
    summarize(count = n()) %>%
    dplyr::mutate(proportion = count / sum(count)) %>%
    dplyr::mutate(cell_type = factor(cell_type, levels = c("CD4+ T cells", "CD8+ T cells", "CD14+ Monocytes", "NK cells", "B cells", "CD16+ Monocytes", "Dendritic cells",  "Erythroid-like cells", "Platelets"))) %>%
    dplyr::arrange(cell_type) %>%
    dplyr::select(-count) %>%
    na.omit() %>%
    tidyr::pivot_wider(names_from = cell_type, values_from = proportion)
} 

tet2_for_radar = group_for_radar(tet2_for_radar) 
dnmt3a_for_radar = group_for_radar(dnmt3a_for_radar)

make_radar = function(data, sample_genotype) {
  colors = c()
  if (sample_genotype == "TET2") {
    colors = brewer.pal(6, "Paired")[c(2,4,3)]
  } else {
    colors = brewer.pal(6, "Paired")[c(2,6,5)]
  }
  (radar_plot = ggradar(data %>% ungroup(MUTATION.GROUP) %>% dplyr::select(-MUTATION.GROUP), 
                  values.radar = c(0, 0.5, 0.75),
                  grid.min = 0, grid.mid = 0.2, grid.max = 1,
                  group.line.width = 0.75,
                  group.point.size = 1.5,
                  group.colours = colors,
                  background.circle.colour = "white",
                  gridline.mid.colour = "grey",
                  legend.position = "bottom") +
    ggplot2::theme(plot.margin = ggplot2::margin(0, 3, 0, 3, 'cm')) +
    ggplot2::coord_cartesian(clip = "off") +
    ggtitle(sample_genotype))
  
  filename = paste0(output_dir, "radar_", sample_genotype, "_mutant_data")
  save_plot(radar_plot, filename, height = 4, width = 6, png = TRUE)
  write_tsv(data, paste0("tables/radar_mutant_", sample_genotype, "_data.tsv"))
}

make_radar(tet2_for_radar, "TET2")
make_radar(dnmt3a_for_radar, "DNMT3A")


```


# Plot UMAP.
```{r}

# All patients plot ---------------------------------------------------------

length(unique(diet_seurat_trimmed@meta.data$cell_type))
(all_data_umap = ggplot2::ggplot(diet_seurat_trimmed@meta.data, ggplot2::aes(x = UMAP_1, y = UMAP_2, fill = cell_type)) +
    geom_point(color = "white", size = 1, shape = 21, stroke = 0.05) +
    ggplot2::scale_fill_manual(values = brewer.pal(9, "Paired")) +
    format_add_just_arrows +
    labs(fill = "Cell type"))

filename = paste0(output_dir, "umap_all_data")
save_plot(all_data_umap, filename, height = 4, width = 6, png = TRUE)

```


# Plot heatmap.
```{r}
annotated_seurat = readRDS("rds_objects/final_annotated_object.rds")

annotated_seurat@meta.data$cell_type[annotated_seurat@meta.data$cell_type == "CD14 Monos"] = "CD14+ Monocytes"
annotated_seurat@meta.data$cell_type[annotated_seurat@meta.data$cell_type == "CD16 Monos"] = "CD16+ Monocytes"
annotated_seurat@meta.data$cell_type[annotated_seurat@meta.data$cell_type == "B"] = "B cells"
annotated_seurat@meta.data$cell_type[annotated_seurat@meta.data$cell_type == "NK"] = "NK cells"

num_cell_per_type = 500
num_top_genes = 10

cells_to_sample = annotated_seurat@meta.data %>%
  group_by(cell_type) %>%
  sample_n(num_cell_per_type) %>%
  pull(cell_ID)

heatmap_data = annotated_seurat[, cells_to_sample]

Idents(heatmap_data) = "cell_type"
pbmc_markers = FindAllMarkers(heatmap_data, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
top_10 = pbmc_markers %>%
  group_by(cluster) %>%
  top_n(n = 10, wt = avg_log2FC)

(heatmap = DoHeatmap(heatmap_data, features = top_10$gene, raster = FALSE, size = 4, group.bar.height = 0) + 
    guides(color = "none"))

filename = "figures/cell_identity_heatmap"
save_plot(heatmap, filename, width = 7, height = 13, png = TRUE)

```

# Plot feature plots.
```{r}
seurat_with_umap = readRDS("rds_objects/seurat_df_harmony_keep_0_75_no_doublets.rds")

Idents(seurat_with_umap) = "STIM"
unstim_data = subset(seurat_with_umap, idents = "VEH")

features = c("IL7R", "LYZ", "CD14", "MS4A1", "CD8A", "GNLY", "NKG7", "CST3", "PPBP")
plots = FeaturePlot(seurat_with_umap, features = features, combine = FALSE)

for (i in 1:length(plots)) {
  if (i != 6) {
    plots[[i]] = plots[[i]] + NoLegend() + format_no_axes
  } else {
    plots[[i]] = plots[[i]] + format_no_axes
  }
}

(feature_plot = cowplot::plot_grid(plotlist = plots))
filename = paste0(output_dir, "feature_canonical")
save_plot(feature_plot, filename, height = 8, width = 8, png = TRUE)

```

# Plot violin.
```{r}
Idents(diet_seurat_trimmed) = "MUTATION.GROUP"

tet2_diet_seurat_trimmed = subset(diet_seurat_trimmed, ident = c("TET2", "Control"))
dnmt3a_diet_seurat_trimmed = subset(diet_seurat_trimmed, ident = c("DNMT3A", "Control"))


Idents(tet2_diet_seurat_trimmed) = "STIM"
Idents(dnmt3a_diet_seurat_trimmed) = "STIM"

tet2_diet_seurat_trimmed_stim = subset(tet2_diet_seurat_trimmed, ident = c("STIM"))
dnmt3a_diet_seurat_trimmed_stim = subset(dnmt3a_diet_seurat_trimmed, ident = c("STIM"))
tet2_diet_seurat_trimmed_veh = subset(tet2_diet_seurat_trimmed, ident = c("VEH"))
dnmt3a_diet_seurat_trimmed_veh = subset(dnmt3a_diet_seurat_trimmed, ident = c("VEH"))

Idents(tet2_diet_seurat_trimmed_veh) = "cell_type"
Idents(dnmt3a_diet_seurat_trimmed_veh) = "cell_type"
Idents(tet2_diet_seurat_trimmed_stim) = "cell_type"
Idents(dnmt3a_diet_seurat_trimmed_stim) = "cell_type"

make_vln_plot = function(data, gene, cell_type, sample_genotype) {
  data@meta.data$MUTATION.GROUP = factor(data@meta.data$MUTATION.GROUP, levels = c("Control", "TET2", "DNMT3A"))
  vln_plot = VlnPlot(data, features = gene, idents = cell_type, group.by = "MUTATION.GROUP", cols = c(brewer.pal(12, "Paired")[2], ifelse(sample_genotype == "TET2", brewer.pal(12, "Paired")[4], brewer.pal(12, "Paired")[6]))) + theme(axis.text.x = element_text(angle = 0, hjust = 0.5), axis.title.x = element_blank())
  save_plot(vln_plot, paste0("figures/violins/", sample_genotype, "_", gsub("\\+", "", gsub(" ", "_", cell_type)), "_", gene, "_violin"), height = 3, width = 4)
}

make_vln_plot(tet2_diet_seurat_trimmed_veh, "FN1", "CD14+ Monocytes", "TET2")
make_vln_plot(tet2_diet_seurat_trimmed_veh, "LDHB", "CD14+ Monocytes", "TET2")
make_vln_plot(dnmt3a_diet_seurat_trimmed_veh, "IFITM2", "CD14+ Monocytes", "DNMT3A")
make_vln_plot(dnmt3a_diet_seurat_trimmed_veh, "PTGER4", "CD14+ Monocytes", "DNMT3A")
make_vln_plot(dnmt3a_diet_seurat_trimmed_veh, "ADGRE5", "CD14+ Monocytes", "DNMT3A")

make_vln_plot(tet2_diet_seurat_trimmed_stim, "SAMD9", "CD14+ Monocytes", "TET2")
make_vln_plot(tet2_diet_seurat_trimmed_stim, "EMP1", "CD14+ Monocytes", "TET2")
make_vln_plot(dnmt3a_diet_seurat_trimmed_stim, "SAMD9", "CD14+ Monocytes", "DNMT3A")
make_vln_plot(tet2_diet_seurat_trimmed_stim, "NRG1", "CD14+ Monocytes", "TET2")
make_vln_plot(dnmt3a_diet_seurat_trimmed_stim, "NRG1", "CD14+ Monocytes", "DNMT3A")
make_vln_plot(dnmt3a_diet_seurat_trimmed_stim, "EMP1", "CD14+ Monocytes", "DNMT3A")


```

# Plot violin have patient stim/unstim side by side.
```{r}
Idents(diet_seurat_trimmed) = "vaf_identifier"
stim_matched_subset = subset(diet_seurat_trimmed, idents = c("TET2 3: 0.062", "TET2 5: 0.3", "TET2 6: 0.33", "TET2 8: 0.51", "DNMT3A 4: 0.08", "DNMT3A 7: 0.13", "DNMT3A 9: 0.24", "Control 2", "Control 3", "Control 4", "Control 5", "Control 7"))
Idents(stim_matched_subset) = "cell_type"


(cxcl8_plot = VlnPlot(stim_matched_subset, features = c("CXCL8"), idents = "CD14+ Monocytes", group.by = "vaf_identifier", split.by = "STIM", cols = brewer.pal(8, "Paired")[c(8,7)]) + theme(axis.title.x = element_blank()))
(il1b_plot = VlnPlot(stim_matched_subset, features = c("IL1B"), idents = "CD14+ Monocytes", group.by = "vaf_identifier", split.by = "STIM", cols = brewer.pal(8, "Paired")[c(8,7)]) + theme(axis.title.x = element_blank()))
(ptgs2_plot = VlnPlot(stim_matched_subset, features = c("PTGS2"), idents = "CD14+ Monocytes", group.by = "vaf_identifier", split.by = "STIM", cols = brewer.pal(8, "Paired")[c(8,7)]) + theme(axis.title.x = element_blank()))

save_plot(cxcl8_plot, "figures/violins/stim_cd14_monos_cxcl8_violin", width = 6)
save_plot(il1b_plot, "figures/violins/stim_cd14_monos_il1b_violin", width = 6)
save_plot(ptgs2_plot, "figures/violins/stim_cd14_monos_ptgs2_violin", width = 6)

```


# Density plot.
```{r}
diet_seurat_trimmed@meta.data$MUTATION.GROUP = factor(diet_seurat_trimmed@meta.data$MUTATION.GROUP, levels = c("Control", "TET2", "DNMT3A"))

(overlaid_plot = ggplot(diet_seurat_trimmed@meta.data, aes(x = UMAP_1, y = UMAP_2)) +
   geom_point(fill = "#bdbdbd", color = "white", size = 1, shape = 21, stroke = 0.05) +
   stat_density2d(aes(alpha = after_stat(level)), fill = brewer.pal(4, "Paired")[2], bins = 5, geom = "polygon") +
   format_add_arrows +
   labs(fill = "Density") +
   facet_wrap(~MUTATION.GROUP))

filename = paste0(output_dir, "density_all_data")
save_plot(overlaid_plot, filename, height = 4, width = 13, png = TRUE)
```

# Plot mutation upset.
```{r}
# this section relies on the changes to diet_seurat_trimmed@meta.data made in the patient level umap section

get_mutations = function(mutation) {
  mutations = str_split(mutation, ", ")
  mutation_vector = lapply(mutations, str_extract, pattern = "[^ ]+")
  return(mutation_vector)
}
 
get_vafs = function(mutation) {
  mutations = str_split(mutation, ", ")
  mutation_vector = lapply(mutations, str_extract, pattern = "\\([^%]+")
  clean_mutation_vector = lapply(mutation_vector, substring, 2)
  numeric_mutation_vector = lapply(clean_mutation_vector, as.numeric)
  return(clean_mutation_vector)
}

mutation_data = diet_seurat_trimmed@meta.data %>%
  dplyr::select(CHIVEID, MUTATION, VAF) %>%
  unique() %>%
  rowwise() %>%
  mutate(Mutations = get_mutations(MUTATION)) %>%
  mutate(VAFs = get_vafs(MUTATION)) %>%
  mutate(Mutation_Group = paste(Mutations %>% unique() %>% sort(), collapse = " "))

write_tsv(mutation_data, "tables/mutation_data.tsv")


mutation_list = mutation_data$Mutations %>% lapply(paste, sep = "&")

# list of sets, each set is a mutation
unique_mutations = mutation_data$Mutations %>% unlist() %>% unique()

tet2_data = c()
srsf2_data = c()
dnmt3a_data = c()
idh2_data = c()
tp53_data = c()
none_data = c()

tet2_vaf = c()
srsf2_vaf = c()
dnmt3a_vaf = c()
idh2_vaf = c()
tp53_vaf = c()
none_vaf = c()

full_data = c("Entry", "VAF", "Mutation_Group")
  
  
for (i in 1:length(mutation_data$Mutations)) {
  entry = mutation_data$Mutations[i] %>% unlist()
  vafs = mutation_data$VAFs[i] %>% unlist()
  mutation_group = mutation_data$Mutation_Group[i]
  
  for (j in 1:length(entry)) {
    sub_entry = entry[j]
    vaf = vafs[j]
    
    new_line = c(sub_entry, as.numeric(vaf), mutation_group)
    full_data = rbind(full_data, new_line)
    
    if ("TET2" == sub_entry) {
      tet2_data = c(tet2_data, i)
      tet2_vaf = c(tet2_vaf, vaf)
    }
    if ("SRSF2" == sub_entry) {
      srsf2_data = c(srsf2_data, i)
      srsf2_vaf = c(srsf2_vaf, vaf)
    }
    if ("DNMT3A" == sub_entry) {
      dnmt3a_data = c(dnmt3a_data, i)
      dnmt3a_vaf = c(dnmt3a_vaf, vaf)
    }
    if ("IDH2" == sub_entry) {
      idh2_data = c(idh2_data, i)
      idh2_vaf = c(idh2_vaf, vaf)
    }
    if ("TP53" == sub_entry) {
      tp53_data = c(tp53_data, i)
      tp53_vaf = c(tp53_vaf, vaf)
    }
    if ("none" == sub_entry) {
      none_data = c(none_data, i)
      none_vaf = c(none_vaf, "0")
    }
  }
}

list_mutation_data = list(
  "TET2" = tet2_data, "SRSF2" = srsf2_data, "DNMT3A" = dnmt3a_data, "IDH2" = idh2_data, "TP53" = tp53_data, "None" = none_data
)
list_vaf_data = list(
  "TET2" = tet2_vaf, "SRSF2" = srsf2_vaf, "DNMT3A" = dnmt3a_vaf, "IDH2" = idh2_vaf, "TP53" = tp53_vaf, "None" = none_vaf
)

library(UpSetR)
(upset_plot = upset(fromList(list_mutation_data), nsets = 7, keep.order = T, mb.ratio = c(0.3, 0.7),
      sets = c("None", "TP53", "IDH2", "SRSF2", "TET2", "DNMT3A"), text.scale = 1.5,
      main.bar.color = brewer.pal(5, "Paired"), mainbar.y.label = element_blank(), mainbar.y.max = 11, sets.x.label = element_blank()))

filename = paste0(output_dir, "upset_mutations")
pdf(file = paste0(filename, ".pdf"), width = 8, height = 2)
print(upset_plot)
write = dev.off()


matrix_mutation_data = plyr::ldply(list_mutation_data, rbind)
write_tsv(matrix_mutation_data, paste0(gsub("figures", "tables", filename), ".tsv"))


colnames(full_data) = full_data[1,]
full_data = full_data[-1,]
full_data[is.na(full_data)] = 0
full_data[full_data == "?ASXL1G645fs"] = "ASXL1"
full_data[full_data == "?ASXL1G645fs TET2"] = "TET2"

full_data = as.data.frame(full_data) %>%
  mutate(VAF = as.numeric(VAF)) %>%
  mutate(Entry = factor(Entry, levels = c("none", "TP53", "IDH2", "SRSF2", "TET2", "DNMT3A"))) %>%
  mutate(Mutation_Group = factor(Mutation_Group, levels = c("DNMT3A", "none", "TET2", "SRSF2 TET2", "DNMT3A IDH2 TP53"))) %>%
  na.omit()


(dot_vafs = ggplot(full_data %>% as.data.frame(), aes(x = Entry, y = VAF)) +
    geom_rect(aes(fill = Entry, xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf, alpha = 0.05), show.legend = FALSE) +
    geom_point(size = 3, aes(color = Mutation_Group)) +
  theme_bw() +
  theme(text = element_text(size = 18), 
        axis.text.x = element_blank(), 
        axis.ticks = element_blank(),
        axis.text.y = element_text(angle = -90, vjust = 1), 
        axis.title.x = element_blank(),
        axis.title.y = element_text(angle = -90),
        panel.border = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        legend.position = "none",
        strip.text = element_blank()) +
    ylab("VAF") +
    scale_y_reverse() +
    scale_color_manual(values = brewer.pal(6, "Paired")) +
    scale_fill_manual(values = c("#f0f0f0", "#ffffff", "#f0f0f0", "#ffffff", "#f0f0f0", "#ffffff", "#f0f0f0")) +
  facet_grid(~Entry, scales = "free"))
filename = paste0(output_dir, "dot_vafs")
save_plot(dot_vafs, filename, height = 3, width = 2)
write_tsv(full_data, paste0(gsub("figures", "tables", filename), ".tsv"))

```

# Represent metacells
```{r}
library(MuDataSeurat)

tet2_stim = ReadH5AD("h5ad_files/tet2_stim_for_seurat.h5ad")
tet2_stim_labels = read_csv("metacells/tet2_stim_metacells.csv")


relevant_metadata = diet_seurat_trimmed@meta.data %>%
  dplyr::select(cell_ID, cell_type, GROUP) %>%
  inner_join(tet2_stim_labels, by = c(cell_ID = "...1")) %>%
  filter(metacell != -1)


relevant_metadata_summarised = relevant_metadata %>%
  group_by(cell_type, GROUP, metacell) %>%
  summarize(count = n())


celltypes_for_metacells = relevant_metadata_summarised %>%
  group_by(GROUP, metacell) %>%
  mutate(proportion = count / sum(count)) %>%
  dplyr::slice(which.max(proportion)) %>%
  filter(proportion >= 0.8)

tet2_stim@meta.data$metacell = rownames(tet2_stim@meta.data) %>% as.numeric()
tet2_stim@meta.data = tet2_stim@meta.data %>%
  inner_join(celltypes_for_metacells)

(metacells_plot = ggplot(tet2_stim@meta.data, aes(x = umap_x, y = umap_y, color = cell_type)) +
  geom_point() +
  theme_bw() +
  scale_color_manual(values = brewer.pal(6, "Paired")) +
  ggtitle("TET2 +IL6 Metacells") +
  labs(color = "Cell type"))

save_plot(metacells_plot, "figures/metacells_plot", width = 6)
```

```{r}
diet_seurat = readRDS("rds_objects/diet_seurat.rds")
seurat_df_harmony_keep_0_75_annotated = readRDS("rds_objects/seurat_df_harmony_keep_0_75_annotated.rds")

pANN = seurat_df_harmony_keep_0_75_annotated@meta.data %>%
  select(starts_with("pANN"))
scores = rowSums(pANN, na.rm = TRUE)
pANN_frame = data.frame(pANN = scores, cell_ID = names(scores))

write_tsv(pANN_frame, "input_data/pANN_frame.tsv")

doublet_score_summary = diet_seurat@meta.data %>%
  inner_join(pANN_frame) %>%
  group_by(CHIVEID, cell_type) %>%
  summarise(median_pANN = median(pANN), sd_pANN = sd(pANN))

library(ggridges)

old_doublet_score = diet_seurat@meta.data %>%
  inner_join(pANN_frame) %>%
  select(CHIVEID, cell_type, cell_ID, pANN, LANE) %>%
  arrange(LANE) 

doublet_score = old_doublet_score %>%
  mutate(CHIVEID = factor(CHIVEID, levels = old_doublet_score$CHIVEID %>% unique()))

ggplot(doublet_score %>% filter(cell_type == "CD14 Monos") %>% filter(!(CHIVEID %in% c("CH-21-031", "CH-21-037", "CH-20-004", "CH-21-014", "CH-21-034", "CH-21-046", "CH-21-020", "CH-21-021", "CH-21-013", "CH-21-008"))), aes(x = pANN, y = CHIVEID)) +
  geom_density_ridges() +
  theme_ridges() + 
  theme(legend.position = "none")
```

