---
title: "metacells2"
output: html_document
date: "2023-04-12"
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/Alyssa/Single_Cell_CHIP/")

library(tidyverse)
library(Seurat)
```

```{r}
# make object smaller

#diet_seurat = DietSeurat(scaled_filtered_annotated_seurat, assays = "RNA")
#saveRDS(diet_seurat, "rds_objects/diet_seurat.rds")

diet_seurat = readRDS("rds_objects/diet_seurat.rds")
counts = LayerData(diet_seurat, assay = "RNA")
counts = diet_seurat@assays$RNA

```


# THIS IS THE ONE THAT WORKS :)
```{r}

tet2_stim_labels = read_csv("metacells/tet2_stim_metacells.csv")
dnmt3a_stim_labels = read_csv("metacells/dnmt3a_stim_metacells.csv")
none_stim_labels = read_csv("metacells/none_stim_metacells.csv")

tet2_veh_labels = read_csv("metacells/tet2_veh_metacells.csv")
dnmt3a_veh_labels = read_csv("metacells/dnmt3a_veh_metacells.csv")
none_veh_labels = read_csv("metacells/none_veh_metacells.csv")


all_labels = rbind(tet2_stim_labels, dnmt3a_stim_labels, none_stim_labels,
                   tet2_veh_labels, dnmt3a_veh_labels, none_veh_labels)

# below is for testing 014 monos compared to controls
# all_labels = rbind(tet2_stim_labels, dnmt3a_stim_labels, none_stim_labels,
#                    tet2_mutant_labels, dnmt3a_veh_labels, none_veh_labels)

```


```{r}
# need some more stringent removal of doublets for one lane
pANN_frame = read_tsv("input_data/pANN_frame.tsv") %>% as.data.frame()
rownames(pANN_frame) = pANN_frame$cell_ID
diet_seurat_trimmed = AddMetaData(diet_seurat, pANN_frame)

cells_to_remove = diet_seurat_trimmed@meta.data %>%
  filter(LANE == "7079-3") %>%
  filter(pANN >= 0.28) %>%
  pull(cell_ID)

diet_seurat_trimmed = diet_seurat_trimmed[,!colnames(diet_seurat_trimmed) %in% cells_to_remove]
saveRDS(diet_seurat_trimmed, "rds_objects/diet_seurat_trimmed.rds")

relevant_metadata = diet_seurat_trimmed@meta.data %>%
  dplyr::select(cell_ID, cell_type, GROUP) %>%
  inner_join(all_labels, by = c(cell_ID = "...1")) %>%
  filter(metacell != -1) %>%
  dplyr::mutate(metacell_labels = paste(gsub(" ", "_", GROUP), metacell, sep = "_") %>% tolower())


relevant_metadata_summarised = relevant_metadata %>%
  group_by(cell_type, GROUP, metacell_labels) %>%
  summarize(count = n())

# use metacells that have 80% or more of one celltype classification
# ignore cells that were not classified as that celltype
# average and perform DE the way that I was doing before with Sam's code


celltypes_for_metacells = relevant_metadata_summarised %>%
  group_by(GROUP, metacell_labels) %>%
  mutate(proportion = count / sum(count)) %>%
  dplyr::slice(which.max(proportion)) %>%
  filter(proportion >= 0.8)

write_tsv(relevant_metadata, "tables/metacells_de/relevant_metadata.tsv")
write_tsv(relevant_metadata_summarised, "tables/metacells_de/relevant_metadata_summarised.tsv")
write_tsv(celltypes_for_metacells, "tables/metacells_de/celltypes_for_metacells.tsv")


```

```{r}
library(DESeq2)
library(SingleCellExperiment)
library(scuttle)
library(apeglm)



aggregate = function(seurat_object) {
    sce = as.SingleCellExperiment(seurat_object, assay = "RNA") # convert to SCE
    agg_sce = aggregateAcrossCells(sce, ids = colData(sce)[,c("GROUP", "metacell")]) # aggregate by metacell
    return(agg_sce)
}


clump = function(agg_sce, label1, label2, shrinkage = TRUE, cell_type) {
    agg_sce = agg_sce[, agg_sce$GROUP %in% c(label1, label2)] # subset on GROUP of interest

    metadata = colData(agg_sce)[,c("GROUP", "metacell")]
    metadata$GROUP = factor(metadata$GROUP, levels = c(label2, label1))
    
    dds = DESeqDataSetFromMatrix(round(assay(agg_sce, "counts")), 
                    colData = metadata, 
                    design = ~ GROUP)
    
    keep = rowSums(counts(dds)) >= 3
    dds = dds[keep,]
    dds = DESeq(dds)
    
    res = results(dds, contrast=c("GROUP", label1, label2))

    summary(res)
    res_ordered_wald = res[order(res$padj),] %>%
      as.data.frame() %>%
      filter(!is.na(padj)) %>%
      rownames_to_column("gene")
    write_tsv(res_ordered_wald, paste0("tables/metacells_de_trimmed/", cell_type, "_", gsub(" ", "_", label1), "_vs_", gsub(" ", "_", label2), ".tsv"))
    return(res_ordered_wald)
}


get_cell_type_data_for_clumping = function(cell_type_name) {
  cell_type_metadata = relevant_metadata %>%
    filter(cell_type == cell_type_name) %>%
    inner_join(celltypes_for_metacells) # this ensures that we only capture cells that match the highest proportion celltype for the metacell
  cell_type_counts = counts[,cell_type_metadata$cell_ID]
  rownames(cell_type_metadata) = cell_type_metadata$cell_ID
  cell_type_sce = SingleCellExperiment(cell_type_counts, colData = cell_type_metadata)
  assayNames(cell_type_sce) = "counts"

  cell_type_agg_sce = aggregateAcrossCells(cell_type_sce, ids = colData(cell_type_sce)[,c("GROUP", "metacell")])
  cell_type_agg_sce@colData = cell_type_agg_sce@colData[,c(1,2,3,4,6)]
  return(cell_type_agg_sce)
}


```

```{r}
run_chip_comparisons = function(cell_type_name) {

  agg_cell_type_data = get_cell_type_data_for_clumping(cell_type_name)
  cell_type_name = gsub(" ", "_", gsub("+", "", cell_type_name, fixed = TRUE))

  tryCatch({
    tet_veh = clump(agg_cell_type_data, label1 = "TET2 VEH", label2 = "none VEH", cell_type = cell_type_name) 
  }, error = function(cond) {
    message("TET2 VEH comparison failed.")
  })
  tryCatch({
    tet_stim = clump(agg_cell_type_data, label1 = "TET2 STIM", label2 = "none STIM", cell_type = cell_type_name) 
  }, error = function(cond) {
    message("TET2 STIM comparison failed.")  
  })
  tryCatch({ 
    dnmt3a_veh = clump(agg_cell_type_data, label1 = "DNMT3A VEH", label2 = "none VEH", cell_type = cell_type_name) 
  }, error = function(cond) {
    message("DNMT3A VEH comparison failed.")
  })
  tryCatch({ dnmt3a_stim = clump(agg_cell_type_data, label1 = "DNMT3A STIM", label2 = "none STIM", cell_type = cell_type_name) 
  }, error = function(cond) {
    message("DNMT3A STIM comparison failed.")
  })
}


run_chip_comparisons("CD14 Monos")
run_chip_comparisons("CD16 Monos")
run_chip_comparisons("CD8+ T cells")
run_chip_comparisons("CD4+ T cells")
run_chip_comparisons("B")
run_chip_comparisons("NK")
run_chip_comparisons("Erythroid-like cells")
run_chip_comparisons("Platelets")
```


# Filter to remove X/Y/MRP genes (MRP is mitochondrial-ribosomal genes. before we removed mito and ribo but not mito-ribo)
```{r}
filter_results = function(sample_genotype, cell_type, stim_status) {
  cell_type_name = gsub(" ", "_", gsub("+", "", cell_type, fixed = TRUE))
  folder = "tables/metacells_de_trimmed/"
  pattern = paste0("^", cell_type_name, "_", sample_genotype, "_", stim_status, ".*")
  print(pattern)

  input_filename = list.files(folder, pattern)
  if (length(input_filename) == 0) {
    return()
  }
  exp_data = read_tsv(paste0(folder, input_filename))
  remove_list = c("DDX3Y", "HBB", "HBA1", "HBD", "HBZ", "HBG2", "HBG1", "HBG2", "CYB5R3", "HBE1", "HBM", "HBQ1", "XIST", "UTY", "USP9Y", exp_data$gene[grep("MRP", exp_data$gene)])
  filtered_data = exp_data %>%
    filter(!gene %in% remove_list)
  write_tsv(filtered_data, paste0("tables/metacells_de_filtered/", cell_type_name, "_", sample_genotype, "_", stim_status, "_filtered.tsv"))
}

diet_seurat = readRDS("rds_objects/diet_seurat.rds")
cell_types = diet_seurat@meta.data$cell_type %>% unique()

for (genotype in c("TET2", "DNMT3A")) {
  for (cell_type in cell_types) {
    filter_results(genotype, cell_type, "VEH")
    filter_results(genotype, cell_type, "STIM")
  }
}
```

# Compare patient 014 monocytes to control monocytes
```{r}
mono_diet_seurat = subset(diet_seurat, subset = (GROUP == "none VEH" | CHIVEID == "CH-21-014"))
counts = LayerData(mono_diet_seurat, assay = "RNA")
cell_type_name = "CD14 Monos"

cell_type_metadata = relevant_metadata %>%
  filter(cell_type == cell_type_name) %>%
  filter(cell_ID %in% mono_diet_seurat@meta.data$cell_ID) %>%
  inner_join(celltypes_for_metacells) # this ensures that we only capture cells that match the highest proportion celltype for the metacell

cell_type_metadata_summarised = cell_type_metadata %>%
  group_by(metacell_labels) %>%
  summarise(new_count = n()) %>%
  filter(new_count >= 10)

cell_type_metadata = cell_type_metadata %>%
  inner_join(cell_type_metadata_summarised)
  

cell_type_counts = counts[,cell_type_metadata$cell_ID]
rownames(cell_type_metadata) = cell_type_metadata$cell_ID
cell_type_sce = SingleCellExperiment(cell_type_counts, colData = cell_type_metadata)
assayNames(cell_type_sce) = "counts"

cell_type_agg_sce = aggregateAcrossCells(cell_type_sce, ids = colData(cell_type_sce)[,c("GROUP", "metacell")])
cell_type_agg_sce@colData = cell_type_agg_sce@colData[,c(1,2,3,4,6)]
cell_type_name = gsub(" ", "_", gsub("+", "", cell_type_name, fixed = TRUE))
  
mono_comp = clump(cell_type_agg_sce, label1 = "TET2 VEH", label2 = "none VEH", cell_type = cell_type_name) 


```



# Collect mutant vs. wildtype metacell labels.
```{r}

tet2_mutant_labels = read_csv("metacells/tet2_mutant_cd14_monos_metacells.csv") %>%
  mutate(`...1` = paste0("014_", `...1`))
dnmt3a_mutant_labels = read_csv("metacells/dnmt3a_mutant_cd14_monos_metacells.csv") %>%
  mutate(`...1` = paste0("046_", `...1`))

tet2_wildtype_labels = read_csv("metacells/tet2_wildtype_cd14_monos_metacells.csv") %>%
  mutate(`...1` = paste0("014_", `...1`))
dnmt3a_wildtype_labels = read_csv("metacells/dnmt3a_wildtype_cd14_monos_metacells.csv") %>%
  mutate(`...1` = paste0("046_", `...1`))

all_mutant_labels = rbind(tet2_mutant_labels, dnmt3a_mutant_labels, tet2_wildtype_labels, dnmt3a_wildtype_labels) %>%
  filter(metacell > 0) 

```




# Collect relevant mutant metadata.
```{r}
tet2_mutant_data = readRDS("rds_objects/TET2mutant_seu.rds") # can probably do cd14 monos and cd8 t cells (based on cell counts)
dnmt3a_mutant_data = readRDS("rds_objects/DNMT3Amutant_seu.rds") # can probably do cd14 monos/nk/cd8 t cells (based on cell counts)

relevant_mutant_metadata = rbind(tet2_mutant_data@meta.data, dnmt3a_mutant_data@meta.data) %>%
  select(cell_ID, cell_type, CLONE, MUTATION.GROUP) %>%
  inner_join(all_mutant_labels, by = c(cell_ID = "...1")) %>%
  filter(metacell != -1) %>%
  mutate(metacell_labels = paste(MUTATION.GROUP, gsub(" ", "_", CLONE), metacell, sep = "_") %>% tolower())


relevant_mutant_metadata_summarised = relevant_mutant_metadata %>%
  group_by(cell_type, CLONE, metacell_labels) %>%
  summarize(count = n())

# use metacells that have 80% or more of one celltype classification
# ignore cells that were not classified as that celltype
# average and perform DE the way that I was doing before with Sam's code


celltypes_for_mutant_metacells = relevant_mutant_metadata_summarised %>%
  group_by(CLONE, metacell_labels) %>%
  mutate(proportion = count / sum(count)) %>%
  dplyr::slice(which.max(proportion)) %>%
  filter(proportion >= 0.8)

write_tsv(relevant_mutant_metadata, "tables/metacells_de/relevant_mutant_metadata.tsv")
write_tsv(relevant_mutant_metadata_summarised, "tables/metacells_de/relevant_mutant_metadata_summarised.tsv")
write_tsv(celltypes_for_mutant_metacells, "tables/metacells_de/celltypes_for_mutant_metacells.tsv")

```


# Mutant vs wiltype cells.
```{r}


# tet2 patient id = 014
# dnmt3a patient id = 046

run_mutant_de = function(mutant_data, patient_id_addition, cell_type_name, genotype) {
  mutant_counts = LayerData(mutant_data, assay = "RNA")
  colnames(mutant_counts) = paste0(patient_id_addition, "_", colnames(mutant_counts))
  mutant_metadata = relevant_mutant_metadata %>%
    filter(cell_type == cell_type_name) %>%
    filter(cell_ID %in% mutant_data@meta.data$cell_ID) %>%
    inner_join(celltypes_for_mutant_metacells) %>%  # this ensures that we only capture cells that match the highest proportion celltype for the metacell
    inner_join(mutant_data@meta.data)
  
  mutant_counts = mutant_counts[,mutant_metadata$cell_ID]
  rownames(mutant_metadata) = mutant_metadata$cell_ID
  mutant_metadata$GROUP = mutant_metadata$CLONE
  mutant_sce = SingleCellExperiment(mutant_counts, colData = mutant_metadata)
  assayNames(mutant_sce) = "counts"
  
  mutant_agg_sce = aggregateAcrossCells(mutant_sce, ids = colData(mutant_sce)[,c("GROUP", "metacell")])
  mutant_agg_sce@colData = mutant_agg_sce@colData[,c("cell_ID", "cell_type", "metacell", "metacell_labels", "GROUP")]

  cell_type_name = gsub(" ", "_", gsub("+", "", cell_type_name, fixed = TRUE))
  mutant_results = clump(agg_sce = mutant_agg_sce, label1 = "Mutant", label2 = "Wildtype", cell_type = paste0(cell_type_name, "_", genotype), shrink = FALSE)
}

run_mutant_de(mutant_data = tet2_mutant_data, patient_id_addition = "014", cell_type_name = "CD14 Monos", genotype = "TET2")
#run_mutant_de(mutant_data = tet2_mutant_data, patient_id_addition = "014", cell_type_name = "CD8 T cells", genotype = "TET2") # don't have enough cells

run_mutant_de(mutant_data = dnmt3a_mutant_data, patient_id_addition = "046", cell_type_name = "CD14 Monos", genotype = "DNMT3A")
#run_mutant_de(mutant_data = dnmt3a_mutant_data, patient_id_addition = "046", cell_type_name = "CD8 T cells", genotype = "DNMT3A") # don't have enough cells






```

