---
title: "metacells2"
output: html_document
date: "2023-08-18"
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/Alyssa/Single_Cell_CHIP/")

library(tidyverse)
library(Seurat)
```

```{r}
diet_seurat = readRDS("rds_objects/diet_seurat.rds")
counts = diet_seurat@assays$RNA

```


```{r}
file_paths = list.files("ccus_demultiplexed/", "\\.csv$", full.names = TRUE)
all_labels = do.call(rbind, lapply(file_paths, read_csv))

```


```{r}
# need some more stringent removal of doublets for one lane
# pANN_frame = read_tsv("input_data/pANN_frame.tsv") %>% as.data.frame()
# rownames(pANN_frame) = pANN_frame$cell_ID
# diet_seurat_trimmed = AddMetaData(diet_seurat, pANN_frame)
# 
# cells_to_remove = diet_seurat_trimmed@meta.data %>%
#   filter(LANE == "7079-3") %>%
#   filter(pANN >= 0.28) %>%
#   pull(cell_ID)
# 
# diet_seurat_trimmed = diet_seurat_trimmed[,!colnames(diet_seurat_trimmed) %in% cells_to_remove]
# saveRDS(diet_seurat_trimmed, "rds_objects/diet_seurat_trimmed.rds")

diet_seurat_trimmed = readRDS("rds_objects/diet_seurat_trimmed.rds")

# Add CCUS labels.
diet_seurat_trimmed@meta.data$CCUS = "Control"
diet_seurat_trimmed@meta.data$CCUS[diet_seurat_trimmed@meta.data$CHIP == "chip"] = "CHIP"
diet_seurat_trimmed@meta.data$CCUS[diet_seurat_trimmed@meta.data$CHIVEID %in% c("CH-20-004", "CH-21-014", "CH-21-036", "CH-21-073")] = "CCUS"

# Create CCUS group labels.
diet_seurat_trimmed@meta.data$CCUS_GROUP = paste(diet_seurat_trimmed@meta.data$MUTATION.GROUP, diet_seurat_trimmed@meta.data$CCUS, diet_seurat_trimmed@meta.data$STIM, sep = "_")


relevant_metadata = diet_seurat_trimmed@meta.data %>%
  dplyr::select(cell_ID, cell_type, CCUS_GROUP) %>%
  inner_join(all_labels, by = c(cell_ID = "...1")) %>%
  filter(metacell != -1) %>%
  dplyr::mutate(metacell_labels = paste(gsub(" ", "_", CCUS_GROUP), metacell, sep = "_") %>% tolower())


relevant_metadata_summarised = relevant_metadata %>%
  group_by(cell_type, CCUS_GROUP, metacell_labels) %>%
  summarize(count = n())

# use metacells that have 80% or more of one celltype classification
# ignore cells that were not classified as that celltype
# average and perform DE the way that I was doing before with Sam's code

celltypes_for_metacells = relevant_metadata_summarised %>%
  group_by(CCUS_GROUP, metacell_labels) %>%
  mutate(proportion = count / sum(count)) %>%
  dplyr::slice(which.max(proportion)) %>%
  filter(proportion >= 0.8)

#write_tsv(relevant_metadata, "tables/metacells_de/relevant_metadata.tsv")
#write_tsv(relevant_metadata_summarised, "tables/metacells_de/relevant_metadata_summarised.tsv")
#write_tsv(celltypes_for_metacells, "tables/metacells_de/celltypes_for_metacells.tsv")


```

```{r}
library(DESeq2)
library(SingleCellExperiment)
library(scuttle)
library(apeglm)



aggregate = function(seurat_object) {
    sce = as.SingleCellExperiment(seurat_object, assay = "RNA") # convert to SCE
    agg_sce = aggregateAcrossCells(sce, ids = colData(sce)[,c("CCUS_GROUP", "metacell")]) # aggregate by metacell
    return(agg_sce)
}


clump = function(agg_sce, label1, label2, shrinkage = TRUE, cell_type) {
    agg_sce = agg_sce[, agg_sce$CCUS_GROUP %in% c(label1, label2)] # subset on CCUS_GROUP of interest

    metadata = colData(agg_sce)[,c("CCUS_GROUP", "metacell")]
    metadata$CCUS_GROUP = factor(metadata$CCUS_GROUP, levels = c(label2, label1))
    
    dds = DESeqDataSetFromMatrix(round(assay(agg_sce, "counts")), 
                    colData = metadata, 
                    design = ~ CCUS_GROUP)
    
    keep = rowSums(counts(dds)) >= 3
    dds = dds[keep,]
    dds = DESeq(dds)
  
    res = results(dds, contrast=c("CCUS_GROUP", label1, label2))

    summary(res)
    res_ordered_wald = res[order(res$padj),] %>%
      as.data.frame() %>%
      filter(!is.na(padj)) %>%
      rownames_to_column("gene")
    write_tsv(res_ordered_wald, paste0("tables/metacells_de_trimmed_ccus/", cell_type, "_", gsub(" ", "_", label1), "_vs_", gsub(" ", "_", label2), ".tsv"))
    return(res_ordered_wald)
}

get_cell_type_data_for_clumping = function(cell_type_name) {
  cell_type_metadata = relevant_metadata %>%
    filter(cell_type == cell_type_name) %>%
    inner_join(celltypes_for_metacells) # this ensures that we only capture cells that match the highest proportion celltype for the metacell
  cell_type_counts = counts[,cell_type_metadata$cell_ID]
  rownames(cell_type_metadata) = cell_type_metadata$cell_ID
  cell_type_sce = SingleCellExperiment(cell_type_counts, colData = cell_type_metadata)
  assayNames(cell_type_sce) = "counts"

  cell_type_agg_sce = aggregateAcrossCells(cell_type_sce, ids = colData(cell_type_sce)[,c("CCUS_GROUP", "metacell")])
  cell_type_agg_sce@colData = cell_type_agg_sce@colData[,c(1,2,3,4,6)]
  return(cell_type_agg_sce)
}


```

```{r}
run_chip_comparisons = function(cell_type_name) {
  
  #cell_type_name = gsub(" ", "_", gsub("+", "", cell_type_name, fixed = TRUE))
  agg_cell_type_data = get_cell_type_data_for_clumping(cell_type_name)

  tryCatch({
    dnmt3a_ccus_veh = clump(agg_cell_type_data, label1 = "DNMT3A_CCUS_VEH", label2 = "none_Control_VEH", cell_type = cell_type_name) 
  }, error = function(cond) {
    message("DNMT3A_CCUS_VEH comparison failed.")
  })
  tryCatch({
    dnmt3a_ccus_stim = clump(agg_cell_type_data, label1 = "DNMT3A_CCUS_STIM", label2 = "none_Control_STIM", cell_type = cell_type_name) 
  }, error = function(cond) {
    message("DNMT3A_CCUS_STIM comparison failed.")  
  })
  tryCatch({
    dnmt3a_chip_veh = clump(agg_cell_type_data, label1 = "DNMT3A_CHIP_VEH", label2 = "none_Control_VEH", cell_type = cell_type_name) 
  }, error = function(cond) {
    message("DNMT3A_CHIP_VEH comparison failed.")
  })
  tryCatch({
    dnmt3a_chip_stim = clump(agg_cell_type_data, label1 = "DNMT3A_CHIP_STIM", label2 = "none_Control_STIM", cell_type = cell_type_name) 
  }, error = function(cond) {
    message("DNMT3A_CHIP_STIM comparison failed.")  
  })
  
  tryCatch({
    tet2_ccus_veh = clump(agg_cell_type_data, label1 = "TET2_CCUS_VEH", label2 = "none_Control_VEH", cell_type = cell_type_name) 
  }, error = function(cond) {
    message("TET2_CCUS_VEH comparison failed.")
  })
  tryCatch({
    tet2_ccus_stim = clump(agg_cell_type_data, label1 = "TET2_CCUS_STIM", label2 = "none_Control_STIM", cell_type = cell_type_name) 
  }, error = function(cond) {
    message("TET2_CCUS_STIM comparison failed.")  
  })
  tryCatch({
    tet2_chip_veh = clump(agg_cell_type_data, label1 = "TET2_CHIP_VEH", label2 = "none_Control_VEH", cell_type = cell_type_name) 
  }, error = function(cond) {
    message("TET2_CHIP_VEH comparison failed.")
  })
  tryCatch({
    tet2_chip_stim = clump(agg_cell_type_data, label1 = "TET2_CHIP_STIM", label2 = "none_Control_STIM", cell_type = cell_type_name) 
  }, error = function(cond) {
    message("TET2_CHIP_STIM comparison failed.")  
  })
}


run_chip_comparisons("CD14 Monos")
run_chip_comparisons("CD16 Monos")
run_chip_comparisons("CD8+ T cells")
run_chip_comparisons("CD4+ T cells")
run_chip_comparisons("B")
run_chip_comparisons("NK")
run_chip_comparisons("Platelets")
```


# Filter to remove X/Y/MRP genes (MRP is mitochondrial-ribosomal genes. before we removed mito and ribo but not mito-ribo)
```{r}
filter_results = function(sample_genotype, cell_type, stim_status) {
  cell_type_name = gsub(" ", "_", gsub("+", "", cell_type, fixed = TRUE))
  folder = "tables/metacells_de_trimmed_ccus/"
  pattern = paste0("^", cell_type_name, "_", sample_genotype, "_", stim_status, ".*")
  print(pattern)

  input_filename = list.files(folder, pattern)
  if (length(input_filename) == 0) {
    return()
  }
  exp_data = read_tsv(paste0(folder, input_filename))
  remove_list = c("DDX3Y", "HBB", "HBA1", "HBD", "HBZ", "HBG2", "HBG1", "HBG2", "CYB5R3", "HBE1", "HBM", "HBQ1", "XIST", "UTY", "USP9Y", exp_data$gene[grep("MRP", exp_data$gene)])
  filtered_data = exp_data %>%
    filter(!gene %in% remove_list)
  write_tsv(filtered_data, paste0("tables/metacells_de_filtered_ccus/", cell_type_name, "_", sample_genotype, "_", stim_status, "_filtered.tsv"))
}

cell_types = diet_seurat_trimmed@meta.data$cell_type %>% unique()

for (genotype in c("TET2", "DNMT3A")) {
  for (cell_type in cell_types) {
    filter_results(genotype, cell_type, "VEH")
    filter_results(genotype, cell_type, "STIM")
  }
}
```
