---
title: "pathway_analysis"
output: html_document
date: '2023-03-24'
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/Alyssa/Single_Cell_CHIP/")
source("../scripts/image_formatting.R")
library(clusterProfiler)
library(tidyverse)
output_dir = "figures/pathway_analysis/"
output_dir_all = "figures/pathway_analysis_all/"

```

```{r}
# Load cluster profiler input

organism = "org.Hs.eg.db"
library(organism, character.only = TRUE)

find_pathways = function(sample_genotype, cell_type, stim_status, use_cutoff = TRUE) {
  cell_type_name = cell_type #gsub(" ", "_", gsub("+", "", cell_type, fixed = TRUE))
  # load expression data from stats output
  folder = "tables/metacells_de_cell_types/"
  pattern = paste0("^", cell_type_name, "_", sample_genotype) #, "_", stim_status, ".*")
  print(pattern)

  input_filename = list.files(folder, pattern)
  if (length(input_filename) == 0) {
    return()
  }
  exp_data = read_tsv(paste0(folder, input_filename))

  # format gene list
  gene_list = exp_data %>%
    dplyr::select(gene, log2FoldChange) %>%
    dplyr::arrange(desc(log2FoldChange)) %>%
    tibble::deframe()
  
  # written with trycatch to avoid errors with empty lists
  tryCatch({
    # identify enriched pathways
    gse = gseGO(geneList = gene_list, keyType = "SYMBOL", OrgDb = organism, ont = "ALL", minGSSize = 50, maxGSSize = 800, pvalueCutoff = ifelse(use_cutoff, 0.05, 1), nPermSimple = 10000)
    gse_all = gseGO(geneList = gene_list, keyType = "SYMBOL", OrgDb = organism, ont = "ALL", minGSSize = 2, maxGSSize = 800, pvalueCutoff = ifelse(use_cutoff, 0.05, 1), nPermSimple = 10000)



    cell_type_for_title = cell_type
    if (cell_type_for_title == "CD14 Monos") {
      cell_type_for_title = "CD14+ Monocytes"
    } else if (cell_type_for_title == "CD16 Monos") {
      cell_type_for_title = "CD16+ Monocytes"
    } else if (cell_type_for_title == "B") {
      cell_type_for_title = "B cells"
    } else if (cell_type_for_title == "NK") {
      cell_type_for_title = "NK cells"
    }
    
    colors = ifelse(sample_genotype == "TET2", format_colors_desc_tet2, format_colors_desc_dnmt3a)
    
    title = paste0(sample_genotype, " ", cell_type_for_title, ifelse(stim_status == "STIM", " +IL6", ""))
    split_plot = dotplot(gse, showCategory = 5, split = ".sign") +
        colors + 
        ggtitle(title) +
        facet_grid(.~.sign)
    plot = dotplot(gse) +
        colors + 
        ggtitle(title)
    
    split_plot_all = dotplot(gse_all, showCategory = 5, split = ".sign") +
        colors + 
        ggtitle(title) +
        facet_grid(.~.sign)
    plot_all = dotplot(gse_all) +
        colors + 
        ggtitle(title)
    
    
    # save plots
    split_filename = paste0(output_dir, "split_dotplot_", sample_genotype, "_", cell_type_name, ifelse(use_cutoff, "", "_no_cutoff"), "_", stim_status)
    split_filename_all = paste0(output_dir_all, "split_dotplot_", sample_genotype, "_", cell_type_name, ifelse(use_cutoff, "", "_no_cutoff"), "_", stim_status, "_all")
    
    save_plot(split_plot, split_filename, height = 6.5, width = 7)
    save_plot(split_plot_all, split_filename_all, height = 6.5, width = 7)

    gse_filename = paste0("tables/gse_results/", sample_genotype, "_", cell_type_name, ifelse(use_cutoff, "", "_no_cutoff"), "_", stim_status, "_gse.tsv")
    write_tsv(gse@result, gse_filename)
    
    gse_filename_all = paste0("tables/gse_results_all/", sample_genotype, "_", cell_type_name, ifelse(use_cutoff, "", "_no_cutoff"), "_", stim_status, "_gse_all.tsv")
    write_tsv(gse_all@result, gse_filename_all)

  }, error = function(cond) {
    message(cond)
    return("Error rendering plot.")
  })
}


```

```{r}
find_pathways("TET2", "CD14 Monos", stim_status = "VEH")
find_pathways("DNMT3A", "CD14 Monos", stim_status = "VEH")

find_pathways("TET2", "CD4+ T cells", stim_status = "VEH")
find_pathways("DNMT3A", "CD4+ T cells", stim_status = "VEH")

find_pathways("TET2", "CD8+ T cells", stim_status = "STIM")
find_pathways("DNMT3A", "CD8+ T cells", stim_status = "STIM")

```


```{r}
library(future)
plan(multisession)

sample_genotypes = c("DNMT3A", "TET2")
diet_seurat = readRDS("rds_objects/diet_seurat.rds")
cell_types = diet_seurat@meta.data$cell_type %>% unique()

for (sample_genotype in sample_genotypes) {
  for (cell_type in cell_types) {
    future(find_pathways(sample_genotype, cell_type, stim_status = "VEH"))
    future(find_pathways(sample_genotype, cell_type, stim_status = "STIM"))
  }
}
```

# Make upset plot with enriched pathways (split by genotype).
```{r}
library("UpSetR")
folder = "tables/gse_results/"
dnmt3a_pattern = paste0("DNMT3A.*_VEH_gse.tsv")

dnmt3a_veh_files = list.files(folder, dnmt3a_pattern)
dnmt3a_cell_types_in_order = substr(dnmt3a_veh_files,1,nchar(dnmt3a_veh_files)-12)
dnmt3a_veh_data = lapply(paste0(folder, dnmt3a_veh_files), read_tsv)
dnmt3a_veh_data_descriptions = lapply(dnmt3a_veh_data, dplyr::pull, "Description")
names(dnmt3a_veh_data_descriptions) = dnmt3a_cell_types_in_order

(dnmt3a_upset_plot = upset(fromList(dnmt3a_veh_data_descriptions), nsets = 5, sets = dnmt3a_cell_types_in_order))

tet2_pattern = paste0("TET2.*_VEH_gse.tsv")

tet2_veh_files = list.files(folder, tet2_pattern)
tet2_cell_types_in_order = substr(tet2_veh_files,1,nchar(tet2_veh_files)-12)
tet2_veh_data = lapply(paste0(folder, tet2_veh_files), read_tsv)
tet2_veh_data_descriptions = lapply(tet2_veh_data, dplyr::pull, "Description")
names(tet2_veh_data_descriptions) = tet2_cell_types_in_order

(tet2_upset_plot = upset(fromList(tet2_veh_data_descriptions), nsets = 5, sets = tet2_cell_types_in_order))

upset_matrix = fromList(append(tet2_veh_data_descriptions, dnmt3a_veh_data_descriptions))
colnames(upset_matrix) = gsub("_", " ", colnames(upset_matrix))
colnames(upset_matrix) = gsub("B", "B cells", colnames(upset_matrix))
colnames(upset_matrix) = gsub("NK", "NK cells", colnames(upset_matrix))
colnames(upset_matrix) = gsub("CD14 Monos", "CD14+ Monocytes", colnames(upset_matrix))
colnames(upset_matrix) = gsub("CD16 Monos", "CD16+ Monocytes", colnames(upset_matrix))
colnames(upset_matrix) = gsub(" T cells", "+ T cells", colnames(upset_matrix))

(complete_upset_plot = upset(upset_matrix, nsets = 10, order.by = "freq", nintersects = 19, text.scale = 1.5, mb.ratio = c(0.4, 0.6)))

geneset_reference = lapply(append(tet2_veh_data, dnmt3a_veh_data), dplyr::select, "Description", "core_enrichment") %>%
  bind_rows() %>%
  mutate(core_enrichment = strsplit(core_enrichment, "/"))

# this section needs to be run outside of the r markdown because markdowns cant save pdfs this way (unless you run the whole block at once)
filename = paste0(output_dir, "upset_pathways")
pdf(file = paste0(filename, ".pdf"), width = 12, height = 4)
complete_upset_plot
dev.off()
```

# Volcano plots.
```{r}
library(gridExtra)
library(egg)
library(RColorBrewer)
library(ggrepel)

full_geneset_labels = readxl::read_excel("input_data/geneset_labels.xlsx") %>%
  inner_join(geneset_reference, by = c(Pathway = "Description")) %>%
  unnest(core_enrichment) %>%
  unique()

highlight_labels = c("Transport activity", "Endoplasmic reticulum regulation", "Immune response", "Leukocyte activation")
highlight_labels_2 = c("Cell migration", "Cell adhesion", "Chemotaxis")
geneset_labels = full_geneset_labels %>% filter(Label %in% highlight_labels)

get_color = function(gene) {
  color = geneset_labels$Label[geneset_labels$core_enrichment == gene] # there could be many matches here
  return(color[1])
}

plot_volcano = function(sample_genotype, cell_type, stim_status) {
  cell_type_name = gsub(" ", "_", gsub("+", "", cell_type, fixed = TRUE))
  folder = "tables/metacells_de_filtered/"
  pattern = paste0("^", cell_type_name, "_", sample_genotype, "_", stim_status, ".*")
  print(pattern)

  input_filename = list.files(folder, pattern)
  if (length(input_filename) == 0) {
    return()
  }
  exp_data = read_tsv(paste0(folder, input_filename)) %>%
    rowwise() %>%
    mutate(color = get_color(gene))
  exp_data$color[is.na(exp_data$color)] = "Other"
  
  exp_data$color = factor(exp_data$color, levels = c(highlight_labels, "Other"))
  cell_type_for_title = cell_type
  if (cell_type_for_title == "CD14 Monos") {
    cell_type_for_title = "CD14+ Monocytes"
  } else if (cell_type_for_title == "CD16 Monos") {
    cell_type_for_title = "CD16+ Monocytes"
  } else if (cell_type_for_title == "B") {
    cell_type_for_title = "B cells"
  } else if (cell_type_for_title == "NK") {
    cell_type_for_title = "NK cells"
  }
      
  (volcano_plot = ggplot(exp_data %>% arrange(desc(color)), aes(x = log2FoldChange, y = -log10(padj), color = color)) +
    geom_point() +
    theme_bw() +
    xlim(-5,5) +
    ylim(0,40) +
    scale_color_manual(values = c(rev(brewer.pal(12, "Paired")[c(1:4)])[c(1:length(highlight_labels))], "lightgrey")) + #changed to 5:12 for 2
    ggtitle(paste0(sample_genotype, " ", cell_type_for_title, ifelse(stim_status == "STIM", " +IL6", ""))) +
   #  # negative labels
   #  geom_label_repel(data = exp_data %>% arrange(desc(-log10(padj))) %>% filter(log2FoldChange < -1) %>% head(10), aes(label = gene), , size = 3,
   #                   fill = NA, direction = "y", max.overlaps =  Inf, nudge_x = 0.05, segment.alpha = 0.25, force_pull = 0, xlim = c(-4.5,-3.5), ylim = c(15,40),
   #                   show.legend = FALSE, box.padding = 0, segment.linetype = "solid", label.size = 0.08, segment.curvature = -1e-40) +
   # # positive labels
   #  geom_label_repel(data = exp_data %>% arrange(desc(-log10(padj))) %>% filter(log2FoldChange > 1) %>% head(10), aes(label = gene), , size = 3,
   #                   fill = NA, direction = "y", max.overlaps =  Inf, nudge_x = 0.05, segment.alpha = 0.25, force_pull = 0, xlim = c(3.5,4.5), ylim = c(15,40),
   #                   show.legend = FALSE, box.padding = 0, segment.linetype = "solid", label.size = 0.08, segment.curvature = 1e-40) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()))
  return(volcano_plot)
}

```

```{r}
make_combined_plots = function(cell_type) {
  (veh_volcano_tet2 = plot_volcano("TET2", cell_type, stim_status = "VEH") + guides(color = "none"))
  (veh_volcano_dnmt3a = plot_volcano("DNMT3A", cell_type, stim_status = "VEH") + labs(color = "Pathway"))
  veh_combined_volcano = grid.arrange(veh_volcano_tet2, veh_volcano_dnmt3a, ncol = 2, widths = c(3,4))
  cell_type_name = gsub("\\+", "", gsub(" ", "_", tolower(cell_type)))
  save_plot(veh_combined_volcano, paste0("figures/combined_volcanos_no_labels/veh_", cell_type_name,"_combined_volcanos"), height = 5, width = 12, png = TRUE)
  
  (stim_volcano_tet2 = plot_volcano("TET2", cell_type, stim_status = "STIM") + guides(color = "none"))
  (stim_volcano_dnmt3a = plot_volcano("DNMT3A", cell_type, stim_status = "STIM") + labs(color = "Pathway"))
  stim_combined_volcano = grid.arrange(stim_volcano_tet2, stim_volcano_dnmt3a, ncol = 2, widths = c(3,4))
  save_plot(stim_combined_volcano, paste0("figures/combined_volcanos_no_labels/stim_", cell_type_name,"_combined_volcanos"), height = 5, width = 12, png = TRUE)
}

make_combined_plots("CD14 Monos")
make_combined_plots("CD4+ T cells")
make_combined_plots("CD8+ T cells")
make_combined_plots("NK")
make_combined_plots("B")
```
```{r}
make_solo_plots = function(cell_type) {
  cell_type_name = gsub("\\+", "", gsub(" ", "_", tolower(cell_type)))
  (veh_volcano_tet2 = plot_volcano("TET2", cell_type, stim_status = "VEH") + labs(color = "Pathway"))
  save_plot(veh_volcano_tet2, paste0("figures/volcanos/tet2_veh_", cell_type_name,"_volcano"), width = 7, png = TRUE)
  
  (stim_volcano_tet2 = plot_volcano("TET2", cell_type, stim_status = "STIM") + labs(color = "Pathway"))
  save_plot(stim_volcano_tet2, paste0("figures/volcanos/tet2_stim_", cell_type_name,"_volcano"), width = 7, png = TRUE)

  (veh_volcano_dnmt3a = plot_volcano("DNMT3A", cell_type, stim_status = "VEH") + labs(color = "Pathway"))
  save_plot(veh_volcano_dnmt3a, paste0("figures/volcanos/dnmt3a_veh_", cell_type_name,"_volcano"), width = 7, png = TRUE)

  (stim_volcano_dnmt3a = plot_volcano("DNMT3A", cell_type, stim_status = "STIM") + labs(color = "Pathway"))
  save_plot(stim_volcano_dnmt3a, paste0("figures/volcanos/dnmt3a_stim_", cell_type_name,"_volcano"), width = 7, png = TRUE)
}

make_solo_plots("CD14 Monos")
make_solo_plots("CD4+ T cells")
make_solo_plots("CD8+ T cells")
make_solo_plots("NK")
make_solo_plots("B")


```

# Mutant vs wildtype
```{r}
 tet2_mutant_de = read_csv("tables/mutant_wt_de_MAST/fcHurdle_all_samples_TET2_mutant_vs_wt_unstim.csv")

  (volcano_plot = ggplot(tet2_mutant_de, aes(x = coef, y = -log10(fdr))) +
    geom_point() +
    theme_bw() +
    xlim(-1,1) +
    ggtitle(paste("VEH", "TET2", "Monocytes")) +
    # negative labels
    geom_label_repel(data = tet2_mutant_de %>% arrange(desc(-log10(fdr))) %>% filter(coef < -0.3) %>% head(10), aes(label = primerid), size = 3,
                     fill = NA, direction = "y", max.overlaps =  Inf, nudge_x = 0.05, segment.alpha = 0.25, force_pull = 0, xlim = c(-1.75,-.75),
                     show.legend = FALSE, box.padding = 0, segment.linetype = "solid", label.size = 0.08, segment.curvature = -1e-40) +
   # positive labels
    geom_label_repel(data = tet2_mutant_de %>% arrange(desc(-log10(fdr))) %>% filter(coef > 0.3) %>% head(10), aes(label = primerid), size = 3,
                     fill = NA, direction = "y", max.overlaps =  Inf, nudge_x = 0.05, segment.alpha = 0.25, force_pull = 0, xlim = c(.75,1.75),
                     show.legend = FALSE, box.padding = 0, segment.linetype = "solid", label.size = 0.08, segment.curvature = 1e-40) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()))

  dnmt3a_mutant_de = read_csv("tables/mutant_wt_de_MAST/fcHurdle_pooled_DNMT3A_mutant_vs_wt_unstim.csv")

  (volcano_plot = ggplot(dnmt3a_mutant_de, aes(x = coef, y = -log10(fdr))) +
    geom_point() +
    theme_bw() +
    xlim(-1,1) +
    ggtitle(paste("VEH", "DNMT3A", "Monocytes")) +
    # negative labels
    geom_label_repel(data = dnmt3a_mutant_de %>% arrange(desc(-log10(fdr))) %>% filter(coef < -0.3) %>% head(10), aes(label = primerid), size = 3,
                     fill = NA, direction = "y", max.overlaps =  Inf, nudge_x = 0.05, segment.alpha = 0.25, force_pull = 0, xlim = c(-1.75,-.75),
                     show.legend = FALSE, box.padding = 0, segment.linetype = "solid", label.size = 0.08, segment.curvature = -1e-40) +
   # positive labels
    geom_label_repel(data = dnmt3a_mutant_de %>% arrange(desc(-log10(fdr))) %>% filter(coef > 0.3) %>% head(10), aes(label = primerid), size = 3,
                     fill = NA, direction = "y", max.overlaps =  Inf, nudge_x = 0.05, segment.alpha = 0.25, force_pull = 0, xlim = c(.75,1.75),
                     show.legend = FALSE, box.padding = 0, segment.linetype = "solid", label.size = 0.08, segment.curvature = 1e-40) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()))
```
```{r}
# format gene list
tet2_gene_list = tet2_mutant_de %>%
  dplyr::select(primerid, coef) %>%
  na.omit() %>%
  dplyr::arrange(desc(coef)) %>%
  tibble::deframe()

# identify enriched pathways
tet2_gse = gseGO(geneList = tet2_gene_list, keyType = "SYMBOL", OrgDb = organism, ont = "ALL", minGSSize = 50, maxGSSize = 800, pvalueCutoff = 0.05, nPermSimple = 10000)

title = paste("TET2", "CD14+ Monocytes")
(tet2_mut_plot = dotplot(tet2_gse) +
    scale_color_gradient(low = brewer.pal(4, "Paired")[4], high = brewer.pal(3, "Paired")[3]) + 
    ggtitle(title))
save_plot(tet2_mut_plot, "figures/pathway_analysis/tet2_mut_dotplot", height = 5.5, width = 7)
write_tsv(tet2_gse@result, "tables/gse_results_mut/tet2_mut_gse.tsv")
```

```{r}
# format gene list
dnmt3a_gene_list = dnmt3a_mutant_de %>%
  dplyr::select(primerid, coef) %>%
  na.omit() %>%
  dplyr::arrange(desc(coef)) %>%
  tibble::deframe()

# identify enriched pathways
dnmt3a_gse = gseGO(geneList = dnmt3a_gene_list, keyType = "SYMBOL", OrgDb = organism, ont = "ALL", minGSSize = 50, maxGSSize = 800, pvalueCutoff = 0.05, nPermSimple = 10000)

title = paste("DNMT3A", "CD14+ Monocytes")
(dnmt3a_mut_plot = dotplot(dnmt3a_gse) +
    scale_color_gradient(low = brewer.pal(6, "Paired")[6], high = brewer.pal(6, "Paired")[5]) + 
    ggtitle(title))
save_plot(dnmt3a_mut_plot, "figures/pathway_analysis/dnmt3a_mut_dotplot", height = 5.5, width = 7)
write_tsv(dnmt3a_gse@result, "tables/gse_results_mut/dnmt3a_mut_gse.tsv")
```

```{r}

tet2_pattern = paste0("TET2.*_VEH_gse.tsv")

tet2_veh_files = list.files(folder, tet2_pattern)
tet2_cell_types_in_order = substr(tet2_veh_files,1,nchar(tet2_veh_files)-12)
tet2_veh_data = lapply(paste0(folder, tet2_veh_files), read_tsv)


mut_geneset_reference = lapply(append(tet2_mut_data, dnmt3a_mut_data), dplyr::select, "Description", "core_enrichment") %>%
  bind_rows() %>%
  mutate(core_enrichment = strsplit(core_enrichment, "/"))
```



```{r}
plot_volcano = function(sample_genotype) {
  folder = "tables/mutant_wt_de_MAST/"

  input_filename = list.files(folder, sample_genotype)
  if (length(input_filename) == 0) {
    return()
  }
  exp_data = read_csv(paste0(folder, input_filename)) %>%
    rowwise() %>%
    mutate(color = get_color(primerid))
  exp_data$color[is.na(exp_data$color)] = "Other"
  
  exp_data$color = factor(exp_data$color, levels = c(highlight_labels, "Other"))
      
  (volcano_plot = ggplot(exp_data %>% arrange(desc(color)), aes(x = coef, y = -log10(fdr), color = color)) +
    geom_point() +
    theme_bw() +
    xlim(-1,1) +
    scale_color_manual(values = c(rev(brewer.pal(12, "Paired")[c(1:4)])[c(1:length(highlight_labels))], "lightgrey")) + #changed to 5:12 for 2
    ggtitle(sample_genotype) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()))
  return(volcano_plot)
}
```

```{r}


mut_volcano_tet2 = plot_volcano("TET2") + guides(color = "none")
mut_volcano_dnmt3a = plot_volcano("DNMT3A") + labs(color = "Pathway")
mut_combined_volcano = grid.arrange(mut_volcano_tet2, mut_volcano_dnmt3a, ncol = 2, widths = c(3,4))
save_plot(mut_combined_volcano, paste0("figures/combined_volcanos_no_labels/mut_combined_volcanos"), height = 5, width = 12, png = TRUE)


```

