
---
title: "volcano_plots"
output: html_document
date: '2023-10-20'
---

```{r setup}
knitr::opts_knit$set(root.dir = "~/Alyssa/Single_Cell_CHIP/")
source("../scripts/image_formatting.R")
library(clusterProfiler)
library(tidyverse)
output_dir = "figures/pathway_analysis/"
output_dir_all = "figures/pathway_analysis_all/"

```


```{r}
library("UpSetR")
folder = "tables/gse_results/"
dnmt3a_pattern = paste0("DNMT3A.*_VEH_gse.tsv")

dnmt3a_veh_files = list.files(folder, dnmt3a_pattern)
dnmt3a_cell_types_in_order = substr(dnmt3a_veh_files,1,nchar(dnmt3a_veh_files)-12)
dnmt3a_veh_data = lapply(paste0(folder, dnmt3a_veh_files), read_tsv)
dnmt3a_veh_data_descriptions = lapply(dnmt3a_veh_data, dplyr::pull, "Description")
names(dnmt3a_veh_data_descriptions) = dnmt3a_cell_types_in_order

(dnmt3a_upset_plot = upset(fromList(dnmt3a_veh_data_descriptions), nsets = 5, sets = dnmt3a_cell_types_in_order))

tet2_pattern = paste0("TET2.*_VEH_gse.tsv")

tet2_veh_files = list.files(folder, tet2_pattern)
tet2_cell_types_in_order = substr(tet2_veh_files,1,nchar(tet2_veh_files)-12)
tet2_veh_data = lapply(paste0(folder, tet2_veh_files), read_tsv)
tet2_veh_data_descriptions = lapply(tet2_veh_data, dplyr::pull, "Description")
names(tet2_veh_data_descriptions) = tet2_cell_types_in_order

(tet2_upset_plot = upset(fromList(tet2_veh_data_descriptions), nsets = 5, sets = tet2_cell_types_in_order))

upset_matrix = fromList(append(tet2_veh_data_descriptions, dnmt3a_veh_data_descriptions))
colnames(upset_matrix) = gsub("_", " ", colnames(upset_matrix))
colnames(upset_matrix) = gsub("B", "B cells", colnames(upset_matrix))
colnames(upset_matrix) = gsub("NK", "NK cells", colnames(upset_matrix))
colnames(upset_matrix) = gsub("CD14 Monos", "CD14+ Monocytes", colnames(upset_matrix))
colnames(upset_matrix) = gsub("CD16 Monos", "CD16+ Monocytes", colnames(upset_matrix))
colnames(upset_matrix) = gsub(" T cells", "+ T cells", colnames(upset_matrix))

(complete_upset_plot = upset(upset_matrix, nsets = 10, order.by = "freq", nintersects = 19, text.scale = 1.5, mb.ratio = c(0.4, 0.6)))

geneset_reference = lapply(append(tet2_veh_data, dnmt3a_veh_data), dplyr::select, "Description", "core_enrichment") %>%
  bind_rows() %>%
  mutate(core_enrichment = strsplit(core_enrichment, "/"))
```


# Volcano plots.
```{r}
library(gridExtra)
library(egg)
library(RColorBrewer)
library(ggrepel)

plot_volcano = function(sample_genotype, cell_type, stim_status) {
  regex_cell_type_name = gsub("\\+", "\\\\+", cell_type)
  folder = "tables/metacells_de_cell_types/"
  pattern = paste0("^", regex_cell_type_name, "_", sample_genotype)
  print(pattern)

  input_filename = list.files(folder, pattern)
  if (length(input_filename) == 0) {
    return()
  }
  exp_data = read_tsv(paste0(folder, input_filename)) %>%
    rowwise() %>%
    mutate(color = get_color(gene))
  exp_data$color[is.na(exp_data$color)] = "Other"
  
  exp_data$color = factor(exp_data$color, levels = c(highlight_labels, "Other"))
  cell_type_for_title = cell_type
  if (cell_type_for_title == "CD14 Monos") {
    cell_type_for_title = "CD14+ Monocytes"
  } else if (cell_type_for_title == "CD16 Monos") {
    cell_type_for_title = "CD16+ Monocytes"
  } else if (cell_type_for_title == "B") {
    cell_type_for_title = "B cells"
  } else if (cell_type_for_title == "NK") {
    cell_type_for_title = "NK cells"
  }
      
  (volcano_plot = ggplot(exp_data %>% arrange(desc(color)), aes(x = log2FoldChange, y = -log10(padj), color = color)) +
    geom_point() +
    theme_bw() +
    xlim(-3,3) +
    ylim(0,40) +
    scale_color_manual(values = c(rev(brewer.pal(12, "Paired")[c(1:4)])[c(1:length(highlight_labels))], "lightgrey")) + #changed to 5:12 for 2
    ggtitle(paste0(sample_genotype, " ", cell_type_for_title, ifelse(stim_status == "STIM", " +IL6", ""))) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()))
  return(volcano_plot)
}

```

```{r}

full_geneset_labels = readxl::read_excel("input_data/geneset_labels.xlsx") %>%
  inner_join(geneset_reference, by = c(Pathway = "Description")) %>%
  unnest(core_enrichment) %>%
  unique()

highlight_labels = c("Transport activity", "Endoplasmic reticulum regulation", "Immune response", "Leukocyte activation")
highlight_labels_2 = c("Cell migration", "Cell adhesion", "Chemotaxis")
geneset_labels = full_geneset_labels %>% filter(Label %in% highlight_labels)

get_color = function(gene) {
  color = geneset_labels$Label[geneset_labels$core_enrichment == gene] # there could be many matches here
  return(color[1])
}


make_combined_plots = function(cell_type) {
  (veh_volcano_tet2 = plot_volcano("TET2", cell_type, stim_status = "VEH") + guides(color = "none") + theme(plot.title = element_text(face = "bold")))
  (veh_volcano_dnmt3a = plot_volcano("DNMT3A", cell_type, stim_status = "VEH") + labs(color = "Pathway") + theme(legend.position = c(0.35, 0.8), legend.background = element_blank(), legend.key.size = unit(0.15, "cm"), plot.title = element_text(face = "bold")))
  veh_combined_volcano = grid.arrange(veh_volcano_tet2, veh_volcano_dnmt3a, ncol = 2) #, widths = c(3,4)
  cell_type_name = gsub("\\+", "", gsub(" ", "_", tolower(cell_type)))
  save_plot(veh_combined_volcano, paste0("figures/combined_volcanos_no_labels/veh_", cell_type_name,"_combined_volcanos"), height = 4, width = 8, png = TRUE)
}

make_combined_plots("CD14 Monos")
make_combined_plots("CD4+ T cells")
make_combined_plots("CD8+ T cells")
make_combined_plots("NK")
make_combined_plots("B")
```


```{r}
full_geneset_labels = readxl::read_excel("input_data/t_cell_geneset_labels.xlsx") %>%
  inner_join(geneset_reference, by = c(Pathway = "Description")) %>%
  unnest(core_enrichment) %>%
  unique()

highlight_labels = c("Transport activity", "Endoplasmic reticulum regulation", "T cell activation", "Immune response")
geneset_labels = full_geneset_labels %>% filter(Label %in% highlight_labels)

get_color = function(gene) {
  color = geneset_labels$Label[geneset_labels$core_enrichment == gene] # there could be many matches here
  return(color[1])
}


make_combined_plots = function(cell_type) {
  (veh_volcano_tet2 = plot_volcano("TET2", cell_type, stim_status = "VEH") + guides(color = "none") + theme(plot.title = element_text(face = "bold")))
  (veh_volcano_dnmt3a = plot_volcano("DNMT3A", cell_type, stim_status = "VEH") + labs(color = "Pathway") + theme(legend.position = c(0.35, 0.8), legend.background = element_blank(), legend.key.size = unit(0.15, "cm"), plot.title = element_text(face = "bold")))
  veh_combined_volcano = grid.arrange(veh_volcano_tet2, veh_volcano_dnmt3a, ncol = 2) #, widths = c(3,4)
  cell_type_name = gsub("\\+", "", gsub(" ", "_", tolower(cell_type)))
  save_plot(veh_combined_volcano, paste0("figures/combined_volcanos_no_labels/veh_", cell_type_name,"_combined_volcanos"), height = 4, width = 8, png = TRUE)
}


make_combined_plots("CD4+ T cells")
make_combined_plots("CD8+ T cells")

```

