---
output: 
    html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr)
library(tidyverse)
library(kableExtra)
library(openxlsx)
library(table1)


clinical_data = openxlsx::read.xlsx("../input_data/clinical data for brett v5.xlsx")
matched_mutations = read_tsv("../tables/matched_mutations.tsv")

grouped_clinical_data = inner_join(matched_mutations, clinical_data, by = c("orig.ident" = "patient_id"))

grouped_clinical_data$former_smoker[grouped_clinical_data$former_smoker == "yes"] = TRUE
grouped_clinical_data$former_smoker[grouped_clinical_data$former_smoker == "no"] = FALSE
grouped_clinical_data$former_smoker = as.logical(grouped_clinical_data$former_smoker)

grouped_clinical_data$hx_cad[grouped_clinical_data$hx_cad == "yes"] = TRUE
grouped_clinical_data$hx_cad[grouped_clinical_data$hx_cad == "no"] = FALSE
grouped_clinical_data$hx_cad = as.logical(grouped_clinical_data$hx_cad)

grouped_clinical_data$hx_CHF[grouped_clinical_data$hx_CHF == "yes"] = TRUE
grouped_clinical_data$hx_CHF[grouped_clinical_data$hx_CHF == "no"] = FALSE
grouped_clinical_data$hx_CHF = as.logical(grouped_clinical_data$hx_CHF)

continuous_mean <- function(x) {
  with(stats.apply.rounding(stats.default(x), digits=2), c("",  "Mean (SD)"=sprintf("%s (%s)", MEAN, SD)))
}

rndr <- function(x, ...) {
  y <- render.default(x, ...)
  if (is.logical(x)) y[2] else y
}

```

```{r grouped_clinical_data, echo = FALSE, results = 'asis'}


table1(~ Sex + Race + Age + `Hx tobacco use` + `Hx CAD` + `Hx CHF` + `Systolic BP` + `Diastolic BP` + `Heart rate` | 
         MUTATION.GROUP, data = grouped_clinical_data %>%
         rename("Sex" = sex, "Race" = race, "Age" = age_initial_sample_collection, "Hx tobacco use" = former_smoker, 
                "Hx CAD" = hx_cad, "Hx CHF" = hx_CHF, "Systolic BP" = systolic_bp, "Diastolic BP" = diastolic_bp, 
                "Heart rate" = heart_rate), 
         overall = NULL,
         render.continuous = continuous_mean,
         render = rndr)


```
