---
title: "Manual celltype assignment"
output: html_document
---

# Set up.
```{r setup, include = FALSE, out.height="50%"}
knitr::opts_knit$set(root.dir = "~/Alyssa/Single_Cell_CHIP/")

library(Seurat)
library(tidyverse)
```

# Get markers.
```{r}
library(harmony)
seurat_DF = readRDS("rds_objects/seurat_DF.rds")
seurat_DF_Harmony_KEEP = readRDS("rds_objects/seurat_DF_Harmony_KEEP.rds")

seurat_df_harmony_keep = RunUMAP(seurat_DF_Harmony_KEEP, dims = 1:20, reduction = "harmony")
seurat_df_harmony_keep = seurat_df_harmony_keep %>%
  FindNeighbors(reduction = "umap", dims = 1:2)# %>%
seurat_df_harmony_keep = FindClusters(seurat_df_harmony_keep, resolution = 0.05)
seurat_df_harmony_keep_0_75 = FindClusters(seurat_df_harmony_keep, resolution = 0.75)

DimPlot(seurat_df_harmony_keep_0_75, reduction = "umap", label = TRUE)

seurat_df_harmony_keep_markers = FindAllMarkers(seurat_df_harmony_keep, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
write_tsv(seurat_df_harmony_keep_markers, "tables/markers/seurat_df_harmony_keep_markers.tsv")

seurat_df_harmony_keep_0_75_markers = FindAllMarkers(seurat_df_harmony_keep_0_75, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
write_tsv(seurat_df_harmony_keep_0_75_markers, "tables/markers/seurat_df_harmony_keep_0_75.tsv")
saveRDS(seurat_df_harmony_keep_0_75, "rds_objects/seurat_df_harmony_keep_0_75.rds")

Idents(seurat_DF_Harmony_KEEP) = "seurat_clusters"
DimPlot(seurat_DF_Harmony_KEEP, reduction = "harmony", label = TRUE)
DimPlot(seurat_df_harmony_keep_0_25, reduction = "harmony", label = TRUE)

```


# Try scType.
```{r}
# load libraries and functions
install.packages("HGNChelper")
install.packages("openxlsx")
lapply(c("dplyr","Seurat","HGNChelper","openxlsx"), library, character.only = T)

# load gene set preparation function
source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/gene_sets_prepare.R")
# load cell type annotation function
source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/sctype_score_.R")


# DB file
db_ = "https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/ScTypeDB_full.xlsx";
tissue = "Immune system" # e.g. Immune system,Pancreas,Liver,Eye,Kidney,Brain,Lung,Adrenal,Heart,Intestine,Muscle,Placenta,Spleen,Stomach,Thymus 

# prepare gene sets
gs_list = gene_sets_prepare(db_, tissue)

# get cell-type by cell matrix
es.max = sctype_score(scRNAseqData = seurat_df_harmony_keep_0_75[["RNA"]]@scale.data, scaled = TRUE, 
                      gs = gs_list$gs_positive, gs2 = gs_list$gs_negative) 


# merge by cluster
cL_results = do.call("rbind", lapply(unique(seurat_df_harmony_keep_0_75@meta.data$seurat_clusters), function(cl){
    es.max.cl = sort(rowSums(es.max[ ,rownames(seurat_df_harmony_keep_0_75@meta.data[seurat_df_harmony_keep_0_75@meta.data$seurat_clusters==cl, ])]), decreasing = !0)
    head(data.frame(cluster = cl, type = names(es.max.cl), scores = es.max.cl, ncells = sum(seurat_df_harmony_keep_0_75@meta.data$seurat_clusters==cl)), 10)
}))

top_5_sctype_scores = cL_results %>% group_by(cluster) %>% top_n(n = 5, wt = scores)  

sctype_scores = cL_results %>% group_by(cluster) %>% top_n(n = 1, wt = scores)  

# set low-confident (low ScType score) clusters to "unknown"
sctype_scores$type[as.numeric(as.character(sctype_scores$scores)) < sctype_scores$ncells/4] = "Unknown"
View(sctype_scores[,1:3])


seurat_df_harmony_keep_0_75@meta.data$customclassif = ""
for(j in unique(sctype_scores$cluster)){
  cl_type = sctype_scores[sctype_scores$cluster==j,]; 
  seurat_df_harmony_keep_0_75@meta.data$customclassif[seurat_df_harmony_keep_0_75@meta.data$seurat_clusters == j] = as.character(cl_type$type[1])
}

DimPlot(seurat_df_harmony_keep_0_75, reduction = "umap", label = TRUE, repel = TRUE, group.by = 'customclassif')   
```

# Save object.
```{r}
saveRDS(seurat_df_harmony_keep_0_75, "rds_objects/seurat_df_harmony_keep_0_75_annotated.rds")
```

# Subcluster unknown clusters and label with scType.
```{r, fig1, fig.width=10}
seurat_df_harmony_keep_0_75 = readRDS("rds_objects/seurat_df_harmony_keep_0_75_annotated.rds")

Idents(seurat_df_harmony_keep_0_75) = "seurat_clusters"
seurat_df_harmony_keep_0_75 = FindSubCluster(seurat_df_harmony_keep_0_75, 5, graph = "RNA_snn", resolution = 0.5)
View(seurat_df_harmony_keep_0_75@meta.data)

sub_cL_results = do.call("rbind", lapply(unique(seurat_df_harmony_keep_0_75@meta.data$sub.cluster), function(cl) {
    es.max.cl = sort(rowSums(es.max[ ,rownames(seurat_df_harmony_keep_0_75@meta.data[seurat_df_harmony_keep_0_75@meta.data$sub.cluster == cl, ])]), decreasing = !0)
    head(data.frame(cluster = cl, type = names(es.max.cl), scores = es.max.cl, ncells = sum(seurat_df_harmony_keep_0_75@meta.data$sub.cluster == cl)), 10)
}))

sub_sctype_scores = sub_cL_results %>% 
  group_by(cluster) %>% 
  top_n(n = 1, wt = scores)  
View(sub_sctype_scores[,1:3])

# set low-confident (low ScType score) clusters to "unknown" but choosing to ignore here because we are mainly interested in larger grouping (CD4, CD8, etc.)
#sub_sctype_scores$type[as.numeric(as.character(sub_sctype_scores$scores)) < sub_sctype_scores$ncells/4] = "Unknown"

seurat_df_harmony_keep_0_75@meta.data$customclassif = ""
for (j in unique(sub_sctype_scores$cluster)) {
  cl_type = sub_sctype_scores[sub_sctype_scores$cluster==j,]; 
  seurat_df_harmony_keep_0_75@meta.data$customclassif[seurat_df_harmony_keep_0_75@meta.data$sub.cluster == j] = as.character(cl_type$type[1])
}
sum(seurat_df_harmony_keep_0_75@meta.data$customclassif == "Unknown")

Idents(seurat_df_harmony_keep_0_75) = "customclassif"
DimPlot(seurat_df_harmony_keep_0_75 %>% subset(ident = "Classical Monocytes"), reduction = "umap", label = TRUE, repel = TRUE, group.by = "customclassif")  
```

# Dig into unknown cluster.
```{r}
unknown_cluster = seurat_df_harmony_keep_0_75@meta.data %>%
  filter(customclassif == "Unknown")
table(unknown_cluster$CHIVEID)
table(unknown_cluster$LANE)

table(unknown_cluster$predicted.celltype.l2)
table(unknown_cluster$sub.cluster)


cluster_5 = subset(seurat_df_harmony_keep_0_75, subset = seurat_clusters == 5)

DimPlot(cluster_5, reduction = "umap", label = TRUE, repel = TRUE, group.by = "customclassif")  
DimPlot(cluster_5, reduction = "umap", label = TRUE, repel = TRUE, group.by = "sub.cluster")  

```

# Remove cells from the T cell cluster that get labeled as monocytes (probably doublets).
```{r}
seurat_df_harmony_keep_0_75_no_doublets = subset(seurat_df_harmony_keep_0_75, subset = seurat_clusters == 5 & customclassif == "Classical Monocytes", invert = TRUE)
```


# Save object.
```{r}
saveRDS(seurat_df_harmony_keep_0_75_no_doublets, "rds_objects/seurat_df_harmony_keep_0_75_no_doublets.rds")
```

# Save umap coordinates and cell annotations for each ID.
```{r}
seurat_df_harmony_keep_0_75_no_doublets = readRDS("rds_objects/seurat_df_harmony_keep_0_75_no_doublets.rds")
umap_coordinates = as.data.frame(Embeddings(object = seurat_df_harmony_keep_0_75_no_doublets[["umap"]]))

seurat_df_harmony_keep_0_75_no_doublets_metadata = seurat_df_harmony_keep_0_75_no_doublets@meta.data %>%
  select(customclassif) %>%
  merge(umap_coordinates, by = "row.names") %>%
  rename(cell_ID = Row.names, scType_celltype = customclassif)

write_tsv(seurat_df_harmony_keep_0_75_no_doublets_metadata, "tables/markers/integrated_seurat_metadata.tsv")
```


# Remove mito and ribo genes.
```{r}
x_chr_genes = read_csv("input_data/x_genes.csv")

filter_mt_rp = function(seu) {
  DefaultAssay(seu) = "RNA"

  rp_ch = rownames(seu)[grepl("^RPS|^RPL", rownames(seu))]
  mt_ch = rownames(seu)[grepl("^MT-", rownames(seu))]

  seu = subset(seu, features = setdiff(rownames(seu), rp_ch))
  seu = subset(seu, features = setdiff(rownames(seu), mt_ch))
  return(seu)
}

annotated_seurat = readRDS("rds_objects/final_annotated_object.rds")
filtered_annotated_seurat = filter_mt_rp(annotated_seurat)
saveRDS(filtered_annotated_seurat, "rds_objects/filtered_annotated_seurat.rds")
system("gsutil cp rds_objects/filtered_annotated_seurat.rds gs://fc-112f611a-aca5-42eb-9970-5050086b3e8d/Single_Cell_CHIP/rds_objects/")
```

